sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
cache: pip

services:
- mysql

install:
- make install


before_script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST_BRANCH
- echo $TRAVIS_PULL_REQUEST
- echo $BRANCH
- export CURRENT_HEAD=$(git rev-parse HEAD)
- git checkout -b development|| git checkout development
- git pull origin development
- git checkout $CURRENT_HEAD
- git diff --name-only HEAD...$TRAVIS_BRANCH
- git diff --name-only development

script:
- make test
- git diff --name-only development | grep __init__.py | \
  grep accelerator | xargs pep8 --filename accelerator/ --ignore E902; \
  git diff --name-only development | grep accelerator | grep "\.py" | \
  grep -v __init__.py | xargs flake8 --filename accelerator/