sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
cache: pip

services:
- mysql

install:
- make install
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export DEFAULT_BRANCH=development
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST_BRANCH
- echo $TRAVIS_PULL_REQUEST
- echo $BRANCH
- export CURRENT_HEAD=$(git rev-parse HEAD)
- git checkout -b $DEFAULT_BRANCH || git checkout $DEFAULT_BRANCH
- git pull origin $DEFAULT_BRANCH --no-edit
- git checkout -b $BRANCH || git checkout $BRANCH
- git pull origin $BRANCH --no-edit
- git checkout $CURRENT_HEAD

script:
- make test
- make code-check

after_success:
- printenv
- >
  if [ ! "$TRAVIS_PULL_REQUEST" ] && [ "$TRAVIS_BRANCH" = "development" ]; then
    gem install travis -v 1.8.10;
    travis login --org --github-token "$SANTE_GH_TOKEN";
    body='{
    "request": {
    "message": "Triggered by '$TRAVIS_COMMIT_MESSAGE' in django-accelerator",
    "branch":"'$TRAVIS_BRANCH'",
    "config": {
      "script": "echo \"The tests dont need to run.\""
      }
    }}'
    curl -s -X POST \
      -H "Content-Type:application/json" \
      -H "Accept:application/json" \
      -H "Travis-API-Version:3" \
      -H "Authorization:token $(travis token --org)" \
      -d "$body" \
      https://api.travis-ci.org/repo/masschallenge%2Fimpact-api/requests;
  fi;
