version: '3'
services:
  accelerator:
    container_name: accelerator-container
    build: 
      context: .
    volumes:
      - ${PWD}:/srv/www/mc/current:cached
    user: root
    stdin_open: true
    tty: true
    command: >
        /bin/bash
