# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('abbr', models.CharField(max_length=3, unique=True)),
                ('usd_exchange', models.FloatField()),
            ],
            options={
                'db_table': 'accelerator_currency',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
