# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-02 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_INTERESTCATEGORY_MODEL),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True, help_text='Which of our Program Families would you like to be involved with?', related_name='interested_entrepreneurprofile', to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_RECOMMENDATIONTAG_MODEL),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_INTERESTCATEGORY_MODEL),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True, help_text='Which of our Program Families would you like to be involved with?', related_name='interested_expertprofile', to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_RECOMMENDATIONTAG_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_INTERESTCATEGORY_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True, help_text='Which of our Program Families would you like to be involved with?', related_name='interested_memberprofile', to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True, to=settings.ACCELERATOR_RECOMMENDATIONTAG_MODEL),
        ),
    ]
