# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 16:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission

from accelerator.utils import create_mc_permission


def add_mc_permissions(apps, schema_editor):
    permissions = Permission.objects.filter(
        content_type__app_label='accelerator')
    for permission in permissions:
        create_mc_permission(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mc_permissions,
                             migrations.RunPython.noop)
    ]
