# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 16:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import (
    Group,
    Permission,
)


def add_mc_permissions(apps, schema_editor):
    perms = Permission.objects.filter(content_type__app_label='accelerator')
    for perm in perms:
        ct, _ = ContentType.objects.get_or_create(
            app_label="mc",
            model=perm.content_type.model)
        new_perm, _ = Permission.objects.get_or_create(
            name=perm.name,
            content_type=ct,
            codename=perm.codename)
        for group in perm.group_set.all():
            group.permissions.add(new_perm)
        for user in perm.user_set.all():
            user.user_permissions.add(new_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mc_permissions,
                             migrations.RunPython.noop)
    ]
