# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_startups', to=settings.AUTH_USER_MODEL),
        ),
    ]
