# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-02 16:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission

from accelerator.utils import create_mc_permission


def add_mc_permissions(apps, schema_editor):
    perms = Permission.objects.filter(content_type__app_label='accelerator')
    for perm in perms:
        create_mc_permission(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_mc_permissions,
                             migrations.RunPython.noop)
    ]
