# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-20 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationanswer',
            unique_together=set([('application', 'application_question')]),
        ),
    ]
