# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import swapper


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(
                    choices=[('OLD', 'OLD'), ('MIGRATING', 'MIGRATING'),
                             ('DONE', 'DONE'), ('ERROR', 'ERROR')],
                    default='OLD', max_length=64)),
            ],
            options={
                'db_table': 'accelerator_modelchange',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting('accelerator',
                                                       'ModelChange'),
            },
        ),
        migrations.AlterModelOptions(
            name='userrolemenu',
            options={'managed': True, 'verbose_name': 'User Role Menu',
                     'verbose_name_plural': 'User Role Menus'},
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'InterestCategory')),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_entrepreneurprofile',
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'ProgramFamily')),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'RecommendationTag')),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'InterestCategory')),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_expertprofile',
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'ProgramFamily')),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'RecommendationTag')),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'InterestCategory')),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_memberprofile',
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'ProgramFamily')),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='recommendation_tags',
            field=models.ManyToManyField(blank=True,
                                         to=swapper.get_model_name(
                                             'accelerator',
                                             'RecommendationTag')),
        ),
    ]
