# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0002_remove_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='judgefeedbackcomponent',
            unique_together=set([('judge_feedback', 'feedback_element')]),
        ),
        migrations.AlterIndexTogether(
            name='judgefeedbackcomponent',
            index_together=set([]),
        ),
    ]
