# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0002_joins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url_slug',
            field=models.CharField(
                blank=True,
                default='',
                max_length=64,
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    message='Alphanumeric characters and dashes only.',
                    regex='^[\\w-]+$')]),
        ),
    ]
