# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0002_recommendationtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accelerator.Industry')),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'mc_industry',
                'managed': True,
            },
        ),
    ]
