# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-24 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0003_auto_20180410_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepage',
            name='file',
            field=models.FileField(
                upload_to=settings.CMS_FILE_ROOT + "/%Y-%m"),
        ),
    ]
