# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 08:17
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0003_readd_unique_remove_index_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='judgefeedbackcomponent',
            index_together=set(
                [('id', 'judge_feedback', 'feedback_element', 'answer_text')]),
        ),
        migrations.AlterField(
            model_name='judgeapplicationfeedback',
            name='judging_status',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'No Conflict'),
                         (2, 'Not Judged - Conflict of Interest'),
                         (3, 'Not Judged - Other (eg., no show)')],
                default=1),
        ),

    ]
