# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-03 17:52
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.db import (
    connection,
    migrations,
)


def fix_actstream_contenttypes(apps, schema_editor):
    if ContentType.objects.filter(app_label='mc').count() == 0:
        return
    judgepanelassignment_ct = ContentType.objects.get(
        app_label='mc', model='judgepanelassignment').id
    application_ct = ContentType.objects.get(
        app_label='mc', model='application').id
    refundcode_ct = ContentType.objects.get(
        app_label='mc', model='refundcode').id
    judginground_ct = ContentType.objects.get(
        app_label='mc', model='judginground').id
    judgeapplicationfeedback_ct = ContentType.objects.get(
        app_label='mc', model='judgeapplicationfeedback').id
    startupmentorrelationship_ct = ContentType.objects.get(
        app_label='mc', model='startupmentorrelationship').id
    mentorprogramofficehour_ct = ContentType.objects.get(
        app_label='mc', model='mentorprogramofficehour').id
    paypalpayment_ct = ContentType.objects.get(
        app_label='mc', model='paypalpayment').id
    startup_ct = ContentType.objects.get(
        app_label='mc', model='startup').id
    with connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS=0")
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={judgepanelassignment_ct} "
            "WHERE action_object_content_type_id=18".format(
                judgepanelassignment_ct=judgepanelassignment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={application_ct} "
            "WHERE action_object_content_type_id=30".format(
                application_ct=application_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={refundcode_ct} "
            "WHERE action_object_content_type_id=42".format(
                refundcode_ct=refundcode_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={judginground_ct} "
            "WHERE action_object_content_type_id=47".format(
                judginground_ct=judginground_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={judgeapplicationfeedback_ct} "
            "WHERE action_object_content_type_id=54".format(
                judgeapplicationfeedback_ct=judgeapplicationfeedback_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={startupmentorrelationship_ct} "
            "WHERE action_object_content_type_id=81".format(
                startupmentorrelationship_ct=startupmentorrelationship_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={mentorprogramofficehour_ct} "
            "WHERE action_object_content_type_id=85".format(
                mentorprogramofficehour_ct=mentorprogramofficehour_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={paypalpayment_ct} "
            "WHERE action_object_content_type_id=109".format(
                paypalpayment_ct=paypalpayment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET action_object_content_type_id={startup_ct} "
            "WHERE action_object_content_type_id=27".format(
                startup_ct=startup_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={judgepanelassignment_ct} "
            "WHERE target_content_type_id=18".format(
                judgepanelassignment_ct=judgepanelassignment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={application_ct} "
            "WHERE target_content_type_id=30".format(
                application_ct=application_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={refundcode_ct} "
            "WHERE target_content_type_id=42".format(
                refundcode_ct=refundcode_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={judginground_ct} "
            "WHERE target_content_type_id=47".format(
                judginground_ct=judginground_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={judgeapplicationfeedback_ct} "
            "WHERE target_content_type_id=54".format(
                judgeapplicationfeedback_ct=judgeapplicationfeedback_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={startupmentorrelationship_ct} "
            "WHERE target_content_type_id=81".format(
                startupmentorrelationship_ct=startupmentorrelationship_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={mentorprogramofficehour_ct} "
            "WHERE target_content_type_id=85".format(
                mentorprogramofficehour_ct=mentorprogramofficehour_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={paypalpayment_ct} "
            "WHERE target_content_type_id=109".format(
                paypalpayment_ct=paypalpayment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET target_content_type_id={startup_ct} "
            "WHERE target_content_type_id=27".format(
                startup_ct=startup_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={judgepanelassignment_ct} "
            "WHERE actor_content_type_id=18".format(
                judgepanelassignment_ct=judgepanelassignment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={application_ct} "
            "WHERE actor_content_type_id=30".format(
                application_ct=application_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={refundcode_ct} "
            "WHERE actor_content_type_id=42".format(
                refundcode_ct=refundcode_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={judginground_ct} "
            "WHERE actor_content_type_id=47".format(
                judginground_ct=judginground_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={judgeapplicationfeedback_ct} "
            "WHERE actor_content_type_id=54".format(
                judgeapplicationfeedback_ct=judgeapplicationfeedback_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={startupmentorrelationship_ct} "
            "WHERE actor_content_type_id=81".format(
                startupmentorrelationship_ct=startupmentorrelationship_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={mentorprogramofficehour_ct} "
            "WHERE actor_content_type_id=85".format(
                mentorprogramofficehour_ct=mentorprogramofficehour_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={paypalpayment_ct} "
            "WHERE actor_content_type_id=109".format(
                paypalpayment_ct=paypalpayment_ct))
        cursor.execute(
            "UPDATE actstream_action "
            "SET actor_content_type_id={startup_ct} "
            "WHERE actor_content_type_id=27".format(
                startup_ct=startup_ct))
        cursor.execute("SET FOREIGN_KEY_CHECKS=1")


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0003_auto_20180410_1618'),
    ]

    operations = [
        migrations.RunPython(fix_actstream_contenttypes,
                             migrations.RunPython.noop)
    ]
