# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 18:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0003_add_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='url_slug',
            field=models.CharField(
                blank=True,
                default='',
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '.*\\D.*',
                        'Slug must contain a non-numeral.'),
                    django.core.validators.RegexValidator(
                        re.compile('^[-a-zA-Z0-9_]+\\Z'),
                        ("Enter a valid 'slug' consisting of letters, "
                         "numbers, underscores or hyphens."),
                        'invalid')]),
        ),
    ]
