# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-03 17:52
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.db import (
    connection,
    migrations,
)


def fix_actstream_contenttypes(apps, schema_editor):
    if ContentType.objects.filter(app_label='mc').count() == 0:
        return
    old_baseprofile_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"baseprofile\"")[0].id
    old_program_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"program\"")[0].id
    old_paypalrefund_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"paypalrefund\"")[0].id
    old_panel_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"panel\"")[0].id
    old_judgepanelassignment_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"judgepanelassignment\"")[0].id
    old_application_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"application\"")[0].id
    old_refundcode_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"refundcode\"")[0].id
    old_refundcoderedemption_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"refundcoderedemption\"")[0].id
    old_judginground_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"judginground\"")[0].id
    old_jaf_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"judgeapplicationfeedback\"")[0].id
    old_smr_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"startupmentorrelationship\"")[0].id
    old_mnt_prg_officehour_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"mentorprogramofficehour\"")[0].id
    old_paypalpayment_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"paypalpayment\"")[0].id
    old_startup_ct = ContentType.objects.raw(
        "SELECT id from django_content_type "
        "WHERE app_label=\"accelerator\" "
        "AND model=\"startup\"")[0].id

    judgepanelassignment_ct = ContentType.objects.get(
        app_label='mc', model='judgepanelassignment').id
    application_ct = ContentType.objects.get(
        app_label='mc', model='application').id
    refundcode_ct = ContentType.objects.get(
        app_label='mc', model='refundcode').id
    refundcoderedemption_ct = ContentType.objects.get(
        app_label='mc', model='refundcoderedemption').id
    judginground_ct = ContentType.objects.get(
        app_label='mc', model='judginground').id
    jaf_ct = ContentType.objects.get(
        app_label='mc', model='judgeapplicationfeedback').id
    startupmentorrelationship_ct = ContentType.objects.get(
        app_label='mc', model='startupmentorrelationship').id
    mentorprogramofficehour_ct = ContentType.objects.get(
        app_label='mc', model='mentorprogramofficehour').id
    paypalpayment_ct = ContentType.objects.get(
        app_label='mc', model='paypalpayment').id
    startup_ct = ContentType.objects.get(
        app_label='mc', model='startup').id
    baseprofile_ct = ContentType.objects.get(app_label='mc',
                                             model='baseprofile').id
    program_ct = ContentType.objects.get(app_label='mc', model='program').id
    paypalrefund_ct = ContentType.objects.get(app_label='mc',
                                              model='paypalrefund').id
    panel_ct = ContentType.objects.get(app_label='mc', model='panel').id
    with connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS=0")
        for part in ('action_object', 'actor', 'target'):
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={application_ct} WHERE "
                "{part}_content_type_id={old_application_ct}".format(
                    part=part,
                    application_ct=application_ct,
                    old_application_ct=old_application_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={judgepanelassignment_ct} WHERE "
                "{part}_content_type_id={old_judgepanelassignment_ct}".format(
                    part=part,
                    judgepanelassignment_ct=judgepanelassignment_ct,
                    old_judgepanelassignment_ct=old_judgepanelassignment_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={refundcode_ct} WHERE "
                "{part}_content_type_id={old_refundcode_ct}".format(
                    part=part,
                    refundcode_ct=refundcode_ct,
                    old_refundcode_ct=old_refundcode_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={refundcoderedemption_ct} WHERE "
                "{part}_content_type_id={old_refundcoderedemption_ct}".format(
                    part=part,
                    refundcoderedemption_ct=refundcoderedemption_ct,
                    old_refundcoderedemption_ct=old_refundcoderedemption_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={judginground_ct} WHERE "
                "{part}_content_type_id={old_judginground_ct}".format(
                    part=part,
                    judginground_ct=judginground_ct,
                    old_judginground_ct=old_judginground_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={jaf_ct} WHERE "
                "{part}_content_type_id={old_jaf_ct}".format(
                    part=part,
                    jaf_ct=jaf_ct,
                    old_jaf_ct=old_jaf_ct
                ))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={startupmentorrelationship_ct} WHERE "
                "{part}_content_type_id={old_smr_ct}".format(
                    part=part,
                    startupmentorrelationship_ct=startupmentorrelationship_ct,
                    old_smr_ct=old_smr_ct
                ))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={mentorprogramofficehour_ct} WHERE "
                "{part}_content_type_id={old_mnt_prg_officehour_ct}".format(
                    part=part,
                    mentorprogramofficehour_ct=mentorprogramofficehour_ct,
                    old_mnt_prg_officehour_ct=old_mnt_prg_officehour_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={paypalpayment_ct} WHERE "
                "{part}_content_type_id={old_paypalpayment_ct}".format(
                    part=part,
                    paypalpayment_ct=paypalpayment_ct,
                    old_paypalpayment_ct=old_paypalpayment_ct))
            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={startup_ct} WHERE "
                "{part}_content_type_id={old_startup_ct}".format(
                    part=part,
                    startup_ct=startup_ct,
                    old_startup_ct=old_startup_ct))

            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={baseprofile_ct} WHERE "
                "{part}_content_type_id={old_baseprofile_ct}".format(
                    part=part,
                    baseprofile_ct=baseprofile_ct,
                    old_baseprofile_ct=old_baseprofile_ct))

            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={panel_ct} WHERE "
                "{part}_content_type_id={old_panel_ct}".format(
                    part=part,
                    panel_ct=panel_ct,
                    old_panel_ct=old_panel_ct))

            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={paypalrefund_ct} WHERE "
                "{part}_content_type_id={old_paypalrefund_ct}".format(
                    part=part,
                    paypalrefund_ct=paypalrefund_ct,
                    old_paypalrefund_ct=old_paypalrefund_ct))

            cursor.execute(
                "UPDATE actstream_action SET "
                "{part}_content_type_id={program_ct} WHERE "
                "{part}_content_type_id={old_program_ct}".format(
                    part=part,
                    program_ct=program_ct,
                    old_program_ct=old_program_ct))

        cursor.execute("SET FOREIGN_KEY_CHECKS=1")


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0003_auto_20180410_1618'),
    ]

    operations = [
        migrations.RunPython(fix_actstream_contenttypes,
                             migrations.RunPython.noop)
    ]
