# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0004_migrate_program_family_location_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
