# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-02 16:55
from __future__ import unicode_literals

from django.db import migrations


def migrate_office_hours_locations(apps, schema_editor):
    Location = apps.get_model('accelerator',
                              'Location')
    MentorProgramOfficeHour = apps.get_model('accelerator',
                                             'MentorProgramOfficeHour')

    Location.objects.get_or_create(name='Israel - Tel Aviv')
    Location.objects.get_or_create(name='Lounge')
    other_location, _ = Location.objects.get_or_create(name='Other')
    remote_location, _ = Location.objects.get_or_create(name='Remote')
    location_values = set(MentorProgramOfficeHour.objects.values_list(
        "old_location", flat=True))

    program_family_locations = _program_family_locations(location_values)
    for old_location in location_values:
        if old_location in program_family_locations:
            location_name = old_location.replace('MassChallenge ', '')
            if 'Israel' in location_name:
                location_name = 'Israel'
            elif old_location.endswith('Texas'):
                location_name = 'Texas - Austin'
            new_location = Location.objects.get(name=location_name)
        else:
            if old_location.startswith('Remote'):
                new_location = remote_location
            else:
                new_location = other_location
        print("{0} {0}".format(old_location, new_location))
        MentorProgramOfficeHour.objects.filter(
            old_location=old_location).update(location=new_location)


def _program_family_locations(location_values):
    return list(filter(
        lambda x: x.startswith('MassChallenge'), location_values))


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0004_migrate_program_family_location_data'),
    ]

    operations = [
        migrations.RunPython(
            migrate_office_hours_locations,
            migrations.RunPython.noop)
    ]
