# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-27 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0004_migrate_program_family_location_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfamily',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='programfamily',
            name='timezone',
        ),
    ]
