# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-25 07:32
from __future__ import unicode_literals

from django.db import migrations

MISSING_PATH = 'cms-files/'


def move_filepage_files(apps, schema_editor):
    FilePage = apps.get_model('accelerator', 'FilePage')

    for file_page in FilePage.objects.filter(file__isnull=False):
        file_page.file.name = MISSING_PATH + file_page.file.name
        file_page.save()


def move_back_filepage_files(apps, schema_editor):
    FilePage = apps.get_model('accelerator', 'FilePage')

    for file_page in FilePage.objects.filter(file__isnull=False):
        name = file_page.file.name
        file_page.file.name = name.split(MISSING_PATH)[-1]
        file_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0004_filepage_file_alter_storage_and_location'),
    ]

    operations = [
        migrations.RunPython(move_filepage_files,
                             move_back_filepage_files)
    ]
