# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0004_readd_index_change_field_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='newsletter_sender',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='newsletter_sender',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='newsletter_sender',
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='foo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='foo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='foo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='judgeapplicationfeedback',
            name='judging_status',
            field=models.IntegerField(blank=True, choices=[(1, 'No Conflict'), (2, 'Not Judged - Conflict of Interest'), (3, 'Not Judged - Other (eg., no show)')], null=True),
        ),
    ]
