# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 09:09
from __future__ import unicode_literals

from django.db import migrations

PRIVACY_POLICY = 'privacy_policy'


def add_privacy_policy_legal_check(apps, schema_editor):
    LegalCheck = apps.get_model('accelerator', 'LegalCheck')
    LegalCheck.objects.create(
        name=PRIVACY_POLICY,
        title='The MassChallenge Privacy Policy',
        url='https://masschallenge.org/privacy-policy'
    )


def remove_privacy_policy_legal_check(apps, schema_editor):
    LegalCheck = apps.get_model('accelerator', 'LegalCheck')
    LegalCheck.objects.filter(name=PRIVACY_POLICY).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0005_legalcheck_userlegalcheck'),
    ]

    operations = [
        migrations.RunPython(add_privacy_policy_legal_check,
                             remove_privacy_policy_legal_check),

    ]
