# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 08:37
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        (
            'accelerator',
            '0005_revert_field_null_change_fields_on_core_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='foo',
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='newsletter_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='newsletter_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='newsletter_sender',
            field=models.BooleanField(default=False),
        ),
    ]
