# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 09:09
from __future__ import unicode_literals

from django.db import migrations


def add_privacy_policy_legal_check(apps, schema_editor):
    LegalCheck = apps.get_model('accelerator', 'LegalCheck')
    LegalCheck.objects.create(
        name='privacy_notice',
        description='I confirm that I have read and I understand the '
                    '<a href="https://masschallenge.org/privacy-notice" '
                    'target="_blank">Privacy Notice</a>.',
    )
    LegalCheck.objects.create(
        name='competition_anti_harassment_site_rules',
        description=(
            'I agree to be bound by the terms of the '
            '<a href="https://masschallenge.org/competition-rules" '
            'target="_blank">Competition Rules</a> and <a '
            'href="https://masschallenge.org/anti-harassment-policies" '
            'target="_blank">Anti-Harassment Policies</a> (if applicable '
            'to me) and to the <a '
            'href="https://masschallenge.org/website-terms-of-use"'
            'target="_blank">Site Terms of Use</a>.'),
    )


def remove_privacy_policy_legal_check(apps, schema_editor):
    LegalCheck = apps.get_model('accelerator', 'LegalCheck')
    LegalCheck.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0005_legalcheck_userlegalcheck'),
    ]

    operations = [
        migrations.RunPython(add_privacy_policy_legal_check,
                             remove_privacy_policy_legal_check),

    ]
