# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-04 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0005_make_location_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='url_slug',
        ),
    ]
