# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 08:37
from __future__ import unicode_literals

import django.db.models.deletion
import swapper
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        (
            'accelerator', '0006_revert_fields_on_core_profile'),
    ]

    operations = [
        # This change introduced a *correct* data inconsistency
    ]
