# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-21 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0006_add_privacy_notice_legal_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprofile',
            name='privacy_policy_accepted',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='privacy_policy_accepted',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='privacy_policy_accepted',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='privacy_policy_accepted',
        ),
    ]
