# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0006_remove_userrole_url_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfamily',
            name='physical_address',
        ),
        migrations.RemoveField(
            model_name='programfamily',
            name='timezone',
        ),
    ]
