# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 16:01
from __future__ import unicode_literals
import swapper

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0007_remove_privacy_policy_accepted_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('judging_round', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_JUDGINGROUND_MODEL)),
            ],
            options={
                'db_table': 'accelerator_criterion',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting('accelerator',
                                                       'Criterion'),
            },
        ),
        migrations.CreateModel(
            name='CriterionOptionSpec',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=1.0)),
                ('criterion', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_CRITERION_MODEL)),
            ],
            options={
                'db_table': 'accelerator_criterionoptionspec',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting('accelerator',
                                                       'CriterionOptionSpec'),
            },
        ),
        migrations.AlterField(
            model_name='legalcheck',
            name='description',
            field=models.TextField(
                help_text=('Text displayed next to checkbox. '
                           'Use HTML for links.')),
        ),
        migrations.AlterField(
            model_name='legalcheck',
            name='name',
            field=models.CharField(default='',
                                   help_text='Internal name for this check.',
                                   max_length=128, unique=True),
        ),
    ]
