# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0007_change_foreign_key'),
    ]

    operations = [
        # 0007 was removed, no need to revert.
    ]
