# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-13 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0007_remove_privacy_policy_accepted_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BaseCriterionOptionSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('option', models.CharField(max_length=64)),
                ('count', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='legalcheck',
            name='description',
            field=models.TextField(help_text='Text displayed next to checkbox. Use HTML for links.'),
        ),
        migrations.AlterField(
            model_name='legalcheck',
            name='name',
            field=models.CharField(default='', help_text='Internal name for this check.', max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('basecriterion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accelerator.BaseCriterion')),
            ],
            options={
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_CRITERION_MODEL',
            },
            bases=('accelerator.basecriterion',),
        ),
        migrations.CreateModel(
            name='CriterionOptionSpec',
            fields=[
                ('basecriterionoptionspec_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accelerator.BaseCriterionOptionSpec')),
            ],
            options={
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_CRITERIONOPTIONSPEC_MODEL',
            },
            bases=('accelerator.basecriterionoptionspec',),
        ),
        migrations.AddField(
            model_name='basecriterionoptionspec',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCELERATOR_CRITERION_MODEL),
        ),
        migrations.AddField(
            model_name='basecriterion',
            name='judging_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCELERATOR_JUDGINGROUND_MODEL),
        ),
    ]
