# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 09:50
from __future__ import unicode_literals

import swapper
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0008_revert_change_to_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_label',
            field=models.ManyToManyField(to=swapper.get_model_name(
                'accelerator', 'UserLabel')),
        ),
    ]
