# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0009_add_many_to_many_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user_label',
        ),
    ]
