# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-11 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0009_remove_choices_from_old_location_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='old_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
