# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0010_make_old_location_field_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='judge_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Judge Type'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='mentor_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Mentor Type'),
        ),
    ]
