# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0010_revert_added_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='program_families',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='program_families',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='program_families',
        ),
    ]
