# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 10:13
from __future__ import unicode_literals

import swapper
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0011_remove_existing_many_to_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_entrepreneurprofile',
                                         to=swapper.get_model_name(
                                             'accelerator', 'ProgramFamily')),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_expertprofile',
                                         to=swapper.get_model_name(
                                             'accelerator', 'ProgramFamily')),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='program_families',
            field=models.ManyToManyField(blank=True,
                                         help_text='Which of our Program Families would you like to be involved with?',
                                         related_name='interested_memberprofile',
                                         to=swapper.get_model_name(
                                             'accelerator', 'ProgramFamily')),
        ),
    ]
