# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0012_revert_field_removal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='startupattribute',
            name='startup',
        ),
        migrations.DeleteModel(
            name='StartupAttribute',
        ),
    ]
