# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-12 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0012_remove_mentor_program_office_hour_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('judging_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.ACCELERATOR_JUDGINGROUND_MODEL)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.ACCELERATOR_SCENARIO_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allocators',
                'db_table': 'accelerator_allocator',
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_ALLOCATOR_MODEL',
            },
        ),
    ]
