# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-07 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0012_delete_unused_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprogramofficehour',
            name='old_location',
        ),
    ]
