# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-18 10:36
from __future__ import unicode_literals

import django.db.models.deletion
import swapper
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0013_remove_model_startup_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attribute_value', models.TextField(
                    help_text='Stored text representation of the value',
                    verbose_name='Value')),
                ('attribute',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=swapper.get_model_name('accelerator',
                                                             'ProgramStartupAttribute'))),
                ('startup',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=swapper.get_model_name('accelerator',
                                                             'Startup'))),
            ],
            options={
                'verbose_name_plural': 'Startup Attributes',
                'db_table': 'accelerator_startupattribute',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting('accelerator',
                                                       'StartupAttribute'),
            },
        ),
    ]
