# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0013_allocator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categoryheaderpage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='filepage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='siteredirectpage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userrolemenu',
            managers=[
            ],
        ),
    ]
