# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0013_remove_mentorprogramofficehour_old_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='expert_category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='experts',
                to=settings.ACCELERATOR_EXPERTCATEGORY_MODEL,
                verbose_name='I primarily consider myself a(n)'),
        ),
    ]
