# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-18 13:00
from __future__ import unicode_literals

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0014_readd_removed_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketstate',
            name='basis',
            field=models.CharField(
                choices=[('cycle', 'Cycle'), ('program', 'Program'),
                         ('foo', 'Foo')], default='cycle', max_length=20),
        ),
    ]
