# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0015_expert_bio_add_max_length_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmentorrelationship',
            name='mentor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='startup_mentor_relationships',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
