# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0016_judginground_allow_dynamic_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='alumni_eligible_program',
            field=models.BooleanField(default=False,
                                      help_text=(
                                          'Finalists will be added ' +
                                          'to our Global Alumni ' +
                                          'Program upon this ' +
                                          'program being set to "Ended"')),
        ),
    ]
