# Generated by Django 2.2.10 on 2020-04-09 21:24

from django.db import migrations

def add_deferred_user_role(apps, schema_editor):
    UserRole = apps.get_model('accelerator', 'UserRole')
    Program = apps.get_model('accelerator', 'Program')
    ProgramRole = apps.get_model('accelerator', 'ProgramRole')
    for program in Program.objects.all():
        ProgramRole.objects.get_or_create(
            user_role__name=UserRole.DEFERRED_MENTOR, 
            program=program)

class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0016_make_user_role_name_unique'),
    ]

    operations = [
        migrations.RunPython(add_deferred_user_role,
                             migrations.RunPython.noop)
    ]
