# Generated by Django 2.2.10 on 2020-04-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0016_make_user_role_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cycle',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='programs',
                to=settings.ACCELERATOR_PROGRAMCYCLE_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='advertised_final_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='application_final_deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='application_open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='default_application_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='application_type_for',
                to=settings.ACCELERATOR_APPLICATIONTYPE_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='programcycle',
            name='short_name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
