# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0017_add_alumni_program_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfamily',
            name='is_open_for_experts',
            field=models.BooleanField(
                default=False,
                help_text='Whether this ProgramFamily should be available'
                          ' to experts'
            ),
        ),
        migrations.AddField(
            model_name='programfamily',
            name='is_open_for_startups',
            field=models.BooleanField(
                default=False,
                help_text='Whether this ProgramFamily should be available'
                          ' to entrepreneurs'
            ),
        ),
        migrations.AlterField(
            model_name='judginground',
            name='allow_dynamic_allocation',
            field=models.BooleanField(
                default=False,
                help_text='Check this button to allow judges to get new'
                          ' applications without manual allocation by staff.'),
        ),
    ]
