# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 15:41
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def forward(apps, schema_editor):
    ProgramFamily = apps.get_model(
        'accelerator',
        'ProgramFamily'
    )
    is_open = F('is_open')
    ProgramFamily.objects.all().update(
        is_open_for_startups=is_open,
        is_open_for_experts=is_open
    )


def backward(apps, schema_editor):
    ProgramFamily = apps.get_model(
        'accelerator',
        'ProgramFamily'
    )
    ProgramFamily.objects.all().update(
        is_open=F('is_open_for_startups')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0017_add_is_open_for_startups_and_experts'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
