# Generated by Django 2.2.10 on 2020-06-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0019_add_deferred_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='all_masschallenge_events',
            field=models.BooleanField(default=False),
        ),
    ]
