# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 10:53
from __future__ import unicode_literals

from django.db import migrations


def delete_2015_alumni_role(apps, schema_editor):
    ProgramRole = apps.get_model('accelerator', 'ProgramRole')
    ProgramRole.objects.filter(name='2015 Alumni').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0019_migrate_is_open_for_startups_and_experts'),
    ]

    operations = [
        migrations.RunPython(delete_2015_alumni_role,
                             migrations.RunPython.noop)
    ]
