# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0019_migrate_is_open_for_startups_and_experts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfamily',
            name='is_open',
        ),
        migrations.AlterField(
            model_name='programfamily',
            name='is_open_for_experts',
            field=models.BooleanField(default=True, help_text='Whether this ProgramFamily should be available to experts'),
        ),
        migrations.AlterField(
            model_name='programfamily',
            name='is_open_for_startups',
            field=models.BooleanField(default=True, help_text='Whether this ProgramFamily should be available to entrepreneurs'),
        ),
    ]
