# Generated by Django 2.2.10 on 2020-04-30 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0019_add_deferred_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(blank=True, db_table='accelerator_expert_related_mentoringspecialty', help_text='Hold down "Control", or "Command" on a Mac,to select more than one.', related_name='experts', to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL, verbose_name='Mentoring Specialties'),
        ),
    ]
