# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-01 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0019_migrate_is_open_for_startups_and_experts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'managed': True,
                     'verbose_name': 'Application Allocator Criterion',
                     'verbose_name_plural': 'Application Allocator Criteria'}
        ),
        migrations.AlterModelOptions(
            name='criterionoptionspec',
            options={'managed': True,
                     'verbose_name': 'Application Allocator Criterion Option'}
        ),
    ]
