# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 10:53
from __future__ import unicode_literals

from django.db import migrations
from accelerator_abstract.models.base_program import (
    ACTIVE_PROGRAM_STATUS,
    ENDED_PROGRAM_STATUS,
)


def make_ended_israel_programs_alumni_eligible(apps, schema_editor):
    Program = apps.get_model('accelerator', 'Program')
    ended_israel_programs = Program.objects.filter(
        program_family__name="Israel",
        program_status=ENDED_PROGRAM_STATUS)
    for program in ended_israel_programs:
        program.alumni_eligible_program = True
        program.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0020_delete_2015_alumni_program_role'),
    ]

    operations = [
        migrations.RunPython(make_ended_israel_programs_alumni_eligible,
                             migrations.RunPython.noop)
    ]
