# Generated by Django 2.2.10 on 2020-05-20 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0020_auto_20200430_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='startup',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='startup_officehours',
                to=settings.ACCELERATOR_STARTUP_MODEL),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                db_table='accelerator_expert_related_mentoringspecialty',
                help_text=('Hold down "Control", or "Command" on a '
                           'Mac,to select more than one.'),
                related_name='experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='program',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PROGRAM_MODEL),
        ),
    ]
