# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0020_criterion_verbose_names'),
        ('accelerator', '0020_remove_is_open_from_program_family'),
    ]

    operations = [
    ]
