# Generated by Django 2.2.10 on 2020-05-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0020_auto_20200430_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='startup',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='startup_officehours',
                to=settings.ACCELERATOR_STARTUP_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='program',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.ACCELERATOR_PROGRAM_MODEL),
        ),
    ]
