# Generated by Django 2.2.10 on 2020-05-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0021_add_nullable_startup_and_program_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='meeting_info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
