# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0021_remove_is_open_from_program_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='judginground',
            name='collision_detection_mode',
            field=models.CharField(choices=[
                ('scenario', 'Check that applications are not added to a '
                    'scenario twice'),
                ('panel_time', 'Check that applications are not added to the '
                    'same panel time within active scenarios twice'),
                ('panel_slot', 'Check that applications are not added to the '
                    'same panel time and slot within active scenarios twice')],
                default='scenario', max_length=10),
        ),
    ]
