# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0022_add_panel_collision_fields_to_judging_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='overview_deadline_date',
            field=models.DateTimeField(
                blank=True, null=True,
                verbose_name='Overview deadline date (Time in UTC)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='overview_start_date',
            field=models.DateTimeField(
                blank=True, null=True,
                verbose_name='Overview start date (Time in UTC)'),
        ),
    ]
