# Generated by Django 2.2.10 on 2020-06-30 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '023_alter_topics_field_office_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_all_masschallenge_events',
            field=models.BooleanField(default=False),
        ),
    ]
