# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-12 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0023_show_utc_on_program_date_time_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='additional_industries',
            field=models.ManyToManyField(
                db_table='accelerator_expert_related_industry',
                help_text=(
                    'You may select up to 5 related industries. To select '
                    'multiple industries, please press and hold Control (CTRL)'
                    ' on PCs or Command (&#8984;) on Macs.'
                ),
                related_name='secondary_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True,
                db_table='accelerator_startup_related_industry',
                help_text=(
                    'You may select up to 5 related industries. To select '
                    'multiple industries, please press and hold Control (CTRL)'
                    ' on PCs or Command (&#8984;) on Macs.'
                ),
                related_name='secondary_startups',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
    ]
