# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-19 10:31
from __future__ import unicode_literals

from django.db import migrations
from fluent_pages.models import PageLayout


def change_page_layouts_to_use_semantic_templates(apps, schema_editor):
    home_page_layout = PageLayout.objects.filter(
        key='home-page-layout').first()
    simple_page_layout = PageLayout.objects.filter(
        key='simple-layout').first()
    home_page_layout.template_path = 'homepage_layout_semantic.html'
    home_page_layout.save()
    simple_page_layout.template_path = 'simple_layout_semantic.html'
    simple_page_layout.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0024_add_help_text_to_additional_industries_fields'),
    ]

    operations = [
        migrations.RunPython(change_page_layouts_to_use_semantic_templates),
    ]
