# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0024_add_help_text_to_additional_industries_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='gender',
            field=models.CharField(
                choices=[
                    ('f', 'Female'),
                    ('m', 'Male'),
                    ('p', 'Prefer Not To State'),
                    ('o', 'Other'),
                    ('', 'Unknown')],
                default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='gender',
            field=models.CharField(
                choices=[
                    ('f', 'Female'),
                    ('m', 'Male'),
                    ('p', 'Prefer Not To State'),
                    ('o', 'Other'),
                    ('', 'Unknown')],
                default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='gender',
            field=models.CharField(
                choices=[
                    ('f', 'Female'),
                    ('m', 'Male'),
                    ('p', 'Prefer Not To State'),
                    ('o', 'Other'),
                    ('', 'Unknown')],
                default='', max_length=1),
        ),
    ]
