# Generated by Django 2.2.10 on 2020-10-27 15:05

from django.conf import settings
from django.db import migrations, models


HELP_TEXT = ('Hold down "Control", or "Command" on a Mac,'
             'to select more than one.')


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0025_add_user_type_to_nav_tree_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationanswer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                db_table='accelerator_expert_related_mentoringspecialty',
                help_text=HELP_TEXT,
                related_name='experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
    ]
