# Generated by Django 2.2.10 on 2021-01-08 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0026_remove_character_limit_to_application_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Application',
            options={
                'verbose_name_plural': 'Applications',
                'db_table': 'accelerator_application',
                'ordering': ['startup'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ApplicationAnswer',
            options={
                'verbose_name_plural': 'Application Answers',
                'db_table': 'accelerator_applicationanswer',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ApplicationPanelAssignment',
            options={
                'verbose_name_plural':
                    'assignments of startup applications to panel',
                'db_table': 'accelerator_applicationpanelassignment',
                'ordering': ('panel_slot_number',),
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ApplicationQuestion',
            options={
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ApplicationType',
            options={
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='BaseProfile',
            options={
                'db_table': 'accelerator_baseprofile',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='BucketState',
            options={
                'db_table': 'accelerator_bucketstate',
                'ordering': ['sort_order'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='CategoryHeaderPage',
            options={
                'verbose_name': 'Category Header',
                'verbose_name_plural': 'Category Headers',
                'db_table': 'pagetype_accelerator_categoryheaderpage',
                'abstract': False,
                'managed': True,
                'swappable': None,
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.AlterModelOptions(
            name='Clearance',
            options={
                'db_table': 'accelerator_clearance',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Criterion',
            options={
                'verbose_name': 'Application Allocator Criterion',
                'verbose_name_plural': 'Application Allocator Criteria',
                'db_table': 'accelerator_criterion',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='CriterionOptionSpec',
            options={
                'verbose_name': 'Application Allocator Criterion Option',
                'db_table': 'accelerator_criterionoptionspec',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Currency',
            options={
                'db_table': 'accelerator_currency',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='EntrepreneurProfile',
            options={
                'db_table': 'accelerator_entrepreneurprofile',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ExpertCategory',
            options={
                'verbose_name': 'Expert Category',
                'verbose_name_plural': 'Expert Categories',
                'db_table': 'accelerator_expertcategory',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ExpertInterest',
            options={
                'verbose_name_plural': 'Expert Interests',
                'db_table': 'accelerator_expertinterest',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ExpertInterestType',
            options={
                'verbose_name_plural': 'Expert Interest Types',
                'db_table': 'accelerator_expertinteresttype',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ExpertProfile',
            options={
                'db_table': 'accelerator_expertprofile',
                'permissions': (
                    ('change_password',
                     'Can change users passwords directly'),
                ),
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='FilePage',
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'pagetype_accelerator_filepage',
                'abstract': False,
                'managed': True,
                'swappable': None,
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.AlterModelOptions(
            name='FunctionalExpertise',
            options={
                'db_table': 'accelerator_functionalexpertise',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Industry',
            options={
                'verbose_name_plural': 'Industries',
                'db_table': 'accelerator_industry',
                'abstract': False,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='InterestCategory',
            options={
                'verbose_name_plural': 'Interest Categories',
                'db_table': 'accelerator_interestcategory',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JobPosting',
            options={
                'verbose_name_plural': 'Job postings for startups',
                'db_table': 'accelerator_jobposting',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgeApplicationFeedback',
            options={
                'verbose_name_plural': 'Judge Application Feedback',
                'db_table': 'accelerator_judgeapplicationfeedback',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgeAvailability',
            options={
                'verbose_name_plural':
                    'Judge availability for specific '
                    'Panel types, times, locations',
                'db_table': 'accelerator_judgeavailability',
                'ordering': ['panel_time__start_date_time',
                             'panel_type__panel_type',
                             'panel_location__location'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgeFeedbackComponent',
            options={
                'verbose_name_plural': 'Feedback Components',
                'db_table': 'accelerator_judgefeedbackcomponent',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgePanelAssignment',
            options={
                'verbose_name_plural': 'assignments of judge to panel',
                'db_table': 'accelerator_judgepanelassignment',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgeRoundCommitment',
            options={
                'verbose_name_plural':
                    'Judge commitment to participate in a Judging Round',
                'db_table': 'accelerator_judgeroundcommitment',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgingForm',
            options={
                'verbose_name_plural': 'Judging Forms',
                'db_table': 'accelerator_judgingform',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgingFormElement',
            options={
                'verbose_name_plural': 'Judging Form Elements',
                'db_table': 'accelerator_judgingformelement',
                'ordering': ['form_type', 'element_number'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='JudgingRound',
            options={
                'verbose_name_plural': 'Judging Rounds',
                'db_table': 'accelerator_judginground',
                'ordering': ['program__program_status',
                             '-program__end_date',
                             '-end_date_time',
                             'name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='LegalCheck',
            options={
                'verbose_name': 'Legal Check',
                'db_table': 'accelerator_legalcheck',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Location',
            options={
                'verbose_name_plural': 'locations',
                'db_table': 'accelerator_location',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='MemberProfile',
            options={
                'db_table': 'accelerator_memberprofile',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='MentoringSpecialties',
            options={
                'verbose_name': 'Mentoring Specialty',
                'verbose_name_plural': 'Mentoring Specialties',
                'db_table': 'accelerator_mentoringspecialties',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='MentorProgramOfficeHour',
            options={
                'verbose_name': 'Office Hour',
                'db_table': 'accelerator_mentorprogramofficehour',
                'ordering': ['start_date_time'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ModelChange',
            options={
                'db_table': 'accelerator_modelchange',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NamedGroup',
            options={
                'db_table': 'accelerator_namedgroup',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NavTree',
            options={
                'verbose_name_plural': 'NavTrees',
                'db_table': 'accelerator_navtree',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NavTreeItem',
            options={
                'verbose_name_plural': 'NavTreeItems',
                'db_table': 'accelerator_navtreeitem',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Newsletter',
            options={
                'db_table': 'accelerator_newsletter',
                'ordering': ('-created_at', 'name'),
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NewsletterReceipt',
            options={
                'db_table': 'accelerator_newsletterreceipt',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NodePublishedFor',
            options={
                'verbose_name': 'Node is Published For',
                'verbose_name_plural': 'Node is Published For',
                'db_table': 'accelerator_nodepublishedfor',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='NodeSubNavAssociation',
            options={
                'verbose_name': 'Node Sub Navigation Association',
                'verbose_name_plural': 'Node Sub Navigation Associations',
                'db_table': 'accelerator_nodesubnavassociation',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Observer',
            options={
                'verbose_name': 'Observer',
                'verbose_name_plural': 'Observers',
                'db_table': 'accelerator_observer',
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Organization',
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'accelerator_organization',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Panel',
            options={
                'verbose_name_plural': 'Panels',
                'db_table': 'accelerator_panel',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PanelLocation',
            options={
                'verbose_name_plural': 'Panel Locations',
                'db_table': 'accelerator_panellocation',
                'ordering': ['judging_round', 'description'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PanelTime',
            options={
                'verbose_name_plural': 'Panel Times',
                'db_table': 'accelerator_paneltime',
                'ordering': ['judging_round', 'start_date_time'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PanelType',
            options={
                'verbose_name_plural': 'Panel Types',
                'db_table': 'accelerator_paneltype',
                'ordering': ['judging_round', 'description'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Partner',
            options={
                'verbose_name_plural': 'Partners',
                'db_table': 'accelerator_partner',
                'ordering': ['organization__name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PartnerTeamMember',
            options={
                'verbose_name_plural': 'Partner Team Members',
                'db_table': 'accelerator_partnerteammember',
                'ordering': ['team_member__last_name',
                             'team_member__first_name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PayPalPayment',
            options={
                'db_table': 'accelerator_paypalpayment',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='PayPalRefund',
            options={
                'db_table': 'accelerator_paypalrefund',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Program',
            options={
                'verbose_name_plural': 'Programs',
                'db_table': 'accelerator_program',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramCycle',
            options={
                'verbose_name_plural': 'program cycles',
                'db_table': 'accelerator_programcycle',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramFamily',
            options={
                'verbose_name_plural': 'program families',
                'db_table': 'accelerator_programfamily',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramFamilyLocation',
            options={
                'verbose_name': 'Program Family Location',
                'verbose_name_plural': 'Program Family Locations',
                'db_table': 'accelerator_programfamilylocation',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramOverride',
            options={
                'verbose_name_plural': 'Program Overrides',
                'db_table': 'accelerator_programoverride',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramPartner',
            options={
                'verbose_name_plural': 'Program Partner',
                'db_table': 'accelerator_programpartner',
                'ordering': ['program__name',
                             'partner_type__sort_order',
                             'partner'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramPartnerType',
            options={
                'verbose_name_plural': 'Program Partner Types',
                'db_table': 'accelerator_programpartnertype',
                'ordering': ['program', 'sort_order'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramRole',
            options={
                'verbose_name': 'Program Role',
                'verbose_name_plural': 'Program Roles',
                'db_table': 'accelerator_programrole',
                'ordering': ['name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramRoleGrant',
            options={
                'verbose_name': 'Program Role Grant',
                'verbose_name_plural': 'Program Role Grants',
                'db_table': 'accelerator_programrolegrant',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramStartupAttribute',
            options={
                'db_table': 'accelerator_programstartupattribute',
                'ordering': ['program', 'attribute_label'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ProgramStartupStatus',
            options={
                'verbose_name_plural': 'Program Startup Statuses',
                'db_table': 'accelerator_programstartupstatus',
                'ordering': ['program', 'sort_order', 'startup_status'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Question',
            options={
                'db_table': 'accelerator_question',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Reference',
            options={
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='RefundCode',
            options={
                'verbose_name_plural': 'Refund Codes',
                'db_table': 'accelerator_refundcode',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='RefundCodeRedemption',
            options={
                'db_table': 'accelerator_refundcoderedemption',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Scenario',
            options={
                'db_table': 'accelerator_scenario',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ScenarioApplication',
            options={
                'verbose_name_plural': 'Scenario Applications',
                'db_table': 'accelerator_scenarioapplication',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ScenarioJudge',
            options={
                'verbose_name_plural': 'Scenario Judges',
                'db_table': 'accelerator_scenariojudge',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='ScenarioPreference',
            options={
                'db_table': 'accelerator_scenariopreference',
                'ordering': ['priority'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Section',
            options={
                'db_table': 'accelerator_section',
                'ordering': ('newsletter', 'sequence'),
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='Site',
            options={
                'db_table': 'accelerator_site',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='SiteProgramAuthorization',
            options={
                'verbose_name_plural': 'Site Program Authorizations',
                'db_table': 'accelerator_siteprogramauthorization',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='SiteRedirectPage',
            options={
                'verbose_name': 'Site Redirect',
                'verbose_name_plural': 'Site Redirects',
                'db_table': 'pagetype_accelerator_siteredirectpage',
                'abstract': False,
                'managed': True,
                'swappable': None,
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.AlterModelOptions(
            name='Startup',
            options={
                'verbose_name_plural': 'Startups',
                'db_table': 'accelerator_startup',
                'ordering': ['organization__name'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupAttribute',
            options={
                'verbose_name_plural': 'Startup Attributes',
                'db_table': 'accelerator_startupattribute',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupCycleInterest',
            options={
                'db_table': 'accelerator_startupcycleinterest',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupLabel',
            options={
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupMentorRelationship',
            options={
                'verbose_name_plural': 'Startup Mentor Relationships',
                'db_table': 'accelerator_startupmentorrelationship',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupMentorTrackingRecord',
            options={
                'verbose_name': 'Mentor Tracking Record',
                'verbose_name_plural': 'Mentor Tracking Records',
                'db_table': 'accelerator_startupmentortrackingrecord',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupOverrideGrant',
            options={
                'verbose_name_plural': 'Startup Override Grants',
                'db_table': 'accelerator_startupoverridegrant',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupProgramInterest',
            options={
                'db_table': 'accelerator_startupprograminterest',
                'ordering': ['order'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupRole',
            options={
                'db_table': 'accelerator_startuprole',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupStatus',
            options={
                'verbose_name_plural': 'Startup Statuses',
                'db_table': 'accelerator_startupstatus',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='StartupTeamMember',
            options={
                'verbose_name_plural': 'Startup Team Members',
                'db_table': 'accelerator_startupteammember',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='UserLabel',
            options={
                'db_table': 'accelerator_userlabel',
                'ordering': ['label'],
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='UserLegalCheck',
            options={
                'verbose_name': 'User Legal Check',
                'db_table': 'accelerator_userlegalcheck',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='UserRole',
            options={
                'db_table': 'accelerator_userrole',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
        migrations.AlterModelOptions(
            name='UserRoleMenu',
            options={
                'verbose_name': 'User Role Menu',
                'verbose_name_plural': 'User Role Menus',
                'db_table': 'pagetype_accelerator_userrolemenu',
                'abstract': False,
                'managed': True,
                'swappable': None,
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.AlterModelOptions(
            name='Allocator',
            options={
                'verbose_name_plural': 'Allocators',
                'db_table': 'accelerator_allocator',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),

    ]