# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-05 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0026_startup_acknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True,
                db_table='accelerator_startup_related_industry',
                help_text='You may select up to 5 related industries.',
                related_name='secondary_startups',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='video_elevator_pitch_url',
            field=embed_video.fields.EmbedVideoField(
                blank=True,
                help_text=(
                    'Upload your 1-3 minute video pitch to Vimeo or '
                    'Youtube. Paste the shared link here.'),
                max_length=100),
        ),
    ]
