# Generated by Django 2.2.10 on 2021-01-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0026_remove_character_limit_to_application_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='test_field',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
