# Generated by Django 2.2.10 on 2020-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0026_remove_character_limit_to_application_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='birth_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
