# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0027_modify_video_url_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterionoptionspec',
            name='option',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
