# Generated by Django 2.2.10 on 2021-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0027_set_swappable_to_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='test_field',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
