# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-10 21:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0027_modify_video_url_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='linked_in_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='personal_website_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid URL', regex='^[hH][tT][tT][pP][sS]?://(([^/:@]+(:[^/@]+)?@)?([\\w-]+)\\.)+([^/:@]+(:[^/@]+)?@)?([\\w-]+)')], verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=16, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='linked_in_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='personal_website_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid URL', regex='^[hH][tT][tT][pP][sS]?://(([^/:@]+(:[^/@]+)?@)?([\\w-]+)\\.)+([^/:@]+(:[^/@]+)?@)?([\\w-]+)')], verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=16, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='linked_in_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='personal_website_url',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid URL', regex='^[hH][tT][tT][pP][sS]?://(([^/:@]+(:[^/@]+)?@)?([\\w-]+)\\.)+([^/:@]+(:[^/@]+)?@)?([\\w-]+)')], verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=16, verbose_name='Twitter'),
        ),
    ]
