# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-17 21:05
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0028_change_profile_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Suggested size: <400px on the short side', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Suggested size: <400px on the short side', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Suggested size: <400px on the short side', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
    ]
