# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0030_make_criterion_option_spec_option_field_optional'
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startupcycleinterest',
            unique_together=set([('cycle', 'startup')]),
        ),
    ]
