# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            (
                '0031_make_cycle_and_startup_unique'
                '_together_on_startup_cycle_interest'
            )
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True,
                max_length=255,
                verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True,
                max_length=255,
                verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True,
                max_length=255,
                verbose_name='Website'),
        ),
    ]
