# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0031_make_cycle_and_startup_unique_together_on_startup_cycle_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestion',
            name='text_box_lines',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='text_limit',
            field=models.IntegerField(default=500),
        ),
    ]
