# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [(
        'accelerator',
        '0032_add_defaults_to_application_question_text_box_fields'
    ), ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True,
                max_length=40,
                verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True,
                max_length=40,
                verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True,
                max_length=40,
                verbose_name='Twitter'),
        ),
    ]
