# Generated by Django 2.2.18 on 2021-02-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0033_migrate_gender_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programfamily',
            name='use_site_tree_side_nav',
        ),
    ]
