# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0034_change_personal_website_url_to_be_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Submit the three goals you plan to work on with your mentors during the accelerator program.', null=True, verbose_name='Program Goals'),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='other_mentors',
            field=models.TextField(blank=True, help_text='\nAdd any mentors who you meet with and not listed in the MassChallenge\nMentor Directory. Please provide their name, company, and email address below.\n', null=True, verbose_name='Additional Mentors'),
        ),
    ]
