# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0035_navtree_navtreeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtreeitem',
            name='tree',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_NAVTREE_MODEL),
        ),
    ]
