# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models

PROGRAM_GOALS_HELP = "Submit the three goals you plan to "\
                     "work on with your mentors during the "\
                     "accelerator program."

ADDITIONAL_MENTORS_HELP = "\nAdd any mentors who you meet with " \
                        "and not listed in the MassChallenge\n" \
                        "Mentor Directory. Please provide their " \
                        "name, company, and email address below.\n"


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0035_navtree_navtreeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmentorrelationship',
            name='status',
            field=models.CharField(
                choices=[
                    ('Confirmed', 'Confirmed'),
                    ('In Discussions With', 'In Discussions With'),
                    ('Desired', 'Desired')],
                default='Desired',
                max_length=32),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text=PROGRAM_GOALS_HELP,
                null=True,
                verbose_name='Program Goals'),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='other_mentors',
            field=models.TextField(
                blank=True,
                help_text=ADDITIONAL_MENTORS_HELP,
                null=True,
                verbose_name='Additional Mentors'),
        ),
    ]
