# Generated by Django 2.2.10 on 2021-03-03 17:08

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0035_add_deferrable_modal_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeferrableModal',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    null=True)),
                ('is_deferred', models.BooleanField(default=False)),
                ('deferred_to', models.DateTimeField(
                    blank=True,
                    null=True)),
                ('deferrable_modal', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_DEFERRABLEMODAL_MODEL)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deferrable Modal',
                'abstract': False,
                'managed': True,
                'swappable': None,
            },
        ),
    ]
