# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0036_navtreeitem_tree_field_is_navtree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmentorrelationship',
            name='status',
            field=models.CharField(
                choices=[
                    ('Confirmed', 'Confirmed'),
                    ('In Discussions With', 'In Discussions With'),
                    ('Desired', 'Desired')],
                default='Desired',
                max_length=32),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='mentors',
            field=models.ManyToManyField(
                help_text="Select the Mentors you would like to work"
                          " with during the program. Start typing a "
                          "Mentor's name; if they are in the Mentor "
                          "Directory, their name should appear as "
                          "you type. If you don't find the person "
                          "you are looking for, use 'Other Mentors' below.",
                through='accelerator.StartupMentorRelationship',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Registered Mentors'),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='notes',
            field=models.TextField(
                blank=True,
                help_text='Submit the three goals you plan to work '
                          'on with your mentors during the accelerator'
                          ' program.',
                null=True,
                verbose_name='Program Goals'),
        ),
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='other_mentors',
            field=models.TextField(
                blank=True,
                help_text='Add any mentors who you meet with and not'
                          ' listed in the MassChallenge Mentor '
                          'Directory. Please provide their name,'
                          ' company, and email address below.',
                null=True,
                verbose_name='Additional Mentors'),
        ),
    ]
