# Generated by Django 2.2.18 on 2021-03-16 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0037_add_user_type_to_userrolemenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='gender',
        ),
    ]
