# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-04 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0037_change_help_texts_for_notes_and_other_mentors_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfamily',
            name='side_navigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.ACCELERATOR_NAVTREE_MODEL),
        ),
    ]
