# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-14 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0037_change_help_texts_for_notes_and_other_mentors_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judginground',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='judginground',
            name='start_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
