# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-28 16:08
from __future__ import unicode_literals

import swapper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from accelerator_abstract.models.accelerator_model import AcceleratorModel


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0037_change_help_texts_for_notes_and_other_mentors_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navtree',
            name='name',
        ),
        migrations.RemoveField(
            model_name='navtreeitem',
            name='name',
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='active_program',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='program',
            field=models.ManyToManyField(
                blank=True,
                to=swapper.get_model_name(
                    AcceleratorModel.Meta.app_label, "Program")),
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='program_exclude',
            field=models.ManyToManyField(
                blank=True,
                related_name='program_exlusion',
                to=swapper.get_model_name(
                    AcceleratorModel.Meta.app_label, "Program")),
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='program_family',
            field=models.ManyToManyField(
                blank=True,
                to=swapper.get_model_name(
                    AcceleratorModel.Meta.app_label, "ProgramFamily")),
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='program_family_exclude',
            field=models.ManyToManyField(
                blank=True,
                related_name='program_family_exlusion',
                to=swapper.get_model_name(
                    AcceleratorModel.Meta.app_label, "ProgramFamily")),
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='user_role',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=swapper.get_model_name(
                    AcceleratorModel.Meta.app_label, "UserRole")),
        ),
    ]
