# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0037_change_help_texts_for_notes_and_other_mentors_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupmentortrackingrecord',
            name='other_mentors',
            field=models.TextField(
                blank=True,
                help_text='Add any mentors you meet with who are '
                          'not listed in the MassChallenge Mentor '
                          'Directory. Please provide their name, '
                          'company, and email address below.',
                null=True,
                verbose_name='Additional Mentors'),
        ),
    ]
