# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0038_add_permissions_fields_to_nav_tree_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtreeitem',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.ACCELERATOR_USERROLE_MODEL),
        ),
    ]
