# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0039_add_permissions_fields_to_nav_tree_item_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='navtreeitem',
            unique_together=set([('tree', 'title', 'url')]),
        ),
    ]
