# Generated by Django 2.2.18 on 2021-05-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0040_create_core_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='expertprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='gender',
        ),
    ]
