# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 04:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0040_alter_unique_together_for_navtreeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navtreeitem',
            name='user_role',
        ),
        migrations.AddField(
            model_name='navtreeitem',
            name='user_role',
            field=models.ManyToManyField(
                blank=True, to=settings.ACCELERATOR_USERROLE_MODEL),
        ),
    ]
