# Generated by Django 2.2.16 on 2021-05-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0040_create_core_profile_table'),
    ]

    operations = [
        migrations.RunSQL("""UPDATE LOW_PRIORITY IGNORE accelerator_startup 
            SET location_regional = "Massachusetts" 
            WHERE location_regional in ("MASSACHUSETTS (MA)","Massachussetts ","MA", "Ma.");"""),
        migrations.RunSQL("""UPDATE LOW_PRIORITY IGNORE accelerator_startup 
            SET location_regional = "California" WHERE location_regional in ("CA");"""),
        migrations.RunSQL("""UPDATE LOW_PRIORITY IGNORE accelerator_startup 
            SET location_regional = "New York" WHERE location_regional in ("NY");"""),
        migrations.RunSQL("""UPDATE LOW_PRIORITY IGNORE accelerator_startup 
            SET location_regional = "Rhode Island" WHERE location_regional in ("RI")""")
    ]
