# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def create_side_nav_tree(apps, schema_editor):
    NavTree = apps.get_model('accelerator', 'NavTree')
    side_nav_tree = NavTree(
        title="MC Side Nav Tree",
        alias=settings.MC_SIDE_NAV_TREE_ALIAS)
    side_nav_tree.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0041_make_user_role_field_many_to_many'
        ),
    ]

    operations = [
        migrations.RunPython(create_side_nav_tree),
    ]
