# Generated by Django 2.2.10 on 2021-05-25 12:36

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0042_remove_old_gender_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile1',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreprofile_ptr', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_COREPROFILE_MODEL)),
            ],
            options={
                'db_table': 'accelerator_entrepreneurprofile1',
            },
        ),
    ]
