# Generated by Django 2.2.10 on 2021-05-11 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

PRIVACY_CHOICES = [
    ('staff', 'MC Staff Only'),
    ('finalists and staff', 'Finalists and MC Staff'),
    ('public', 'All Users')]

JUDGE_INTEREST_HELP_TEXT = (
    'I would like to participate in MassChallenge as a Judge')
MENTOR_INTEREST_HELP_TEXT = (
    'I would like to participate in MassChallenge as a Mentor')
SPEAKER_INTEREST_HELP_TEXT = (
    'I would like to participate in MassChallenge as a Speaker')
SPEAKER_TOPICS_HELP_TEXT = (
    'Please describe the topic(s) you would be available '
    'to speak about')
OFFICE_HOURS_INTEREST_HELP_TEXT = (
    'I would like to participate in MassChallenge by '
    'holding Office Hours')
OFFICE_HOURS_TOPICS_HELP_TEXT = (
    'Please describe the topic(s) you would be available '
    'to speak to Finalists about during Office Hours')
REFERRED_BY_HELP_TEXT = (
    'If someone referred you to MassChallenge, please provide '
    'their name (and organization if relevant). Otherwise, please'
    ' indicate how you learned about the opportunity to participate'
    ' at MassChallenge (helps us understand the effectiveness of '
    'our outreach programs).')
ADDITIONAL_INDUSTRIES_HELP_TEXT = (
    'You may select up to 5 related industries. To '
    'select multiple industries, please press and hold'
    ' Control (CTRL) on PCs or Command (&#8984;) on Macs.')
POTENTIAL_EXPERTS_HELP_TEXT = (
    "We're always looking for more great experts to join "
    "the MassChallenge community and program. We welcome "
    "the names and contact info (email) of individuals you "
    "think could be great additions to the program, as well "
    "as how you think they might want to be involved "
    "(Judge, Mentor, etc.) Also, please encourage these"
    " individuals to fill out their own Expert Profile.")


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0042_remove_old_gender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreprofile',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True,
                help_text=ADDITIONAL_INDUSTRIES_HELP_TEXT,
                related_name='coreprofile_secondary_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='company',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='expert_category',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coreprofile_experts',
                to=settings.ACCELERATOR_EXPERTCATEGORY_MODEL,
                verbose_name='I primarily consider myself a(n)'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='functional_expertise',
            field=models.ManyToManyField(
                blank=True, related_name='coreprofile_experts',
                to=settings.MPTT_SWAPPABLE_FUNCTIONALEXPERTISE_MODEL,
                verbose_name='Functional Expertise'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='home_program_family',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL,
                verbose_name='Home Program Family'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='judge_interest',
            field=models.BooleanField(
                default=False,
                help_text=JUDGE_INTEREST_HELP_TEXT,
                verbose_name='Judge'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='mentor_interest',
            field=models.BooleanField(
                default=False,
                help_text=MENTOR_INTEREST_HELP_TEXT,
                verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='office_hours_interest',
            field=models.BooleanField(
                default=False,
                help_text=OFFICE_HOURS_INTEREST_HELP_TEXT,
                verbose_name='Office Hours'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='office_hours_topics',
            field=models.TextField(
                blank=True,
                help_text=OFFICE_HOURS_TOPICS_HELP_TEXT,
                verbose_name='Office Hour Topics'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='other_potential_experts',
            field=models.TextField(
                blank=True,
                help_text=POTENTIAL_EXPERTS_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='primary_industry',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'level__exact': 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coreprofile_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Primary Industry'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='privacy_email',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Email'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='privacy_phone',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Phone'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='privacy_web',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Web'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='public_website_consent',
            field=models.BooleanField(
                default=False, verbose_name='Public Website Consent'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='referred_by',
            field=models.TextField(
                blank=True,
                help_text=REFERRED_BY_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='speaker_interest',
            field=models.BooleanField(
                default=False, help_text=SPEAKER_INTEREST_HELP_TEXT,
                verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='speaker_topics',
            field=models.TextField(
                blank=True,
                help_text=SPEAKER_TOPICS_HELP_TEXT,
                verbose_name='Speaker Topics'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='title',
            field=models.CharField(
                blank=True, max_length=255,
                verbose_name='Professional Title'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True, help_text=ADDITIONAL_INDUSTRIES_HELP_TEXT,
                related_name='entrepreneurprofile_secondary_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='company',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='expert_category',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entrepreneurprofile_experts',
                to=settings.ACCELERATOR_EXPERTCATEGORY_MODEL,
                verbose_name='I primarily consider myself a(n)'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='functional_expertise',
            field=models.ManyToManyField(
                blank=True, related_name='entrepreneurprofile_experts',
                to=settings.MPTT_SWAPPABLE_FUNCTIONALEXPERTISE_MODEL,
                verbose_name='Functional Expertise'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='home_program_family',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL,
                verbose_name='Home Program Family'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='judge_interest',
            field=models.BooleanField(
                default=False, help_text=JUDGE_INTEREST_HELP_TEXT,
                verbose_name='Judge'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='mentor_interest',
            field=models.BooleanField(
                default=False, help_text=MENTOR_INTEREST_HELP_TEXT,
                verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='office_hours_interest',
            field=models.BooleanField(
                default=False, help_text=OFFICE_HOURS_INTEREST_HELP_TEXT,
                verbose_name='Office Hours'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='office_hours_topics',
            field=models.TextField(
                blank=True, help_text=OFFICE_HOURS_TOPICS_HELP_TEXT,
                verbose_name='Office Hour Topics'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='other_potential_experts',
            field=models.TextField(
                blank=True,
                help_text=POTENTIAL_EXPERTS_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='primary_industry',
            field=models.ForeignKey(
                blank=True, limit_choices_to={'level__exact': 0}, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entrepreneurprofile_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Primary Industry'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='privacy_email',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Email'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='privacy_phone',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Phone'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='privacy_web',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Web'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='public_website_consent',
            field=models.BooleanField(
                default=False, verbose_name='Public Website Consent'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='referred_by',
            field=models.TextField(
                blank=True,
                help_text=REFERRED_BY_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='speaker_interest',
            field=models.BooleanField(
                default=False, help_text=SPEAKER_INTEREST_HELP_TEXT,
                verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='speaker_topics',
            field=models.TextField(
                blank=True,
                help_text=SPEAKER_TOPICS_HELP_TEXT,
                verbose_name='Speaker Topics'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='title',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Professional Title'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True, help_text=ADDITIONAL_INDUSTRIES_HELP_TEXT,
                related_name='memberprofile_secondary_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='company',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='expert_category',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberprofile_experts',
                to=settings.ACCELERATOR_EXPERTCATEGORY_MODEL,
                verbose_name='I primarily consider myself a(n)'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='functional_expertise',
            field=models.ManyToManyField(
                blank=True, related_name='memberprofile_experts',
                to=settings.MPTT_SWAPPABLE_FUNCTIONALEXPERTISE_MODEL,
                verbose_name='Functional Expertise'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='home_program_family',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL,
                verbose_name='Home Program Family'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='judge_interest',
            field=models.BooleanField(
                default=False, help_text=JUDGE_INTEREST_HELP_TEXT,
                verbose_name='Judge'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='mentor_interest',
            field=models.BooleanField(
                default=False, help_text=MENTOR_INTEREST_HELP_TEXT,
                verbose_name='Mentor'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='office_hours_interest',
            field=models.BooleanField(
                default=False, help_text=OFFICE_HOURS_INTEREST_HELP_TEXT,
                verbose_name='Office Hours'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='office_hours_topics',
            field=models.TextField(
                blank=True, help_text=OFFICE_HOURS_TOPICS_HELP_TEXT,
                verbose_name='Office Hour Topics'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='other_potential_experts',
            field=models.TextField(
                blank=True,
                help_text=POTENTIAL_EXPERTS_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='primary_industry',
            field=models.ForeignKey(
                blank=True, limit_choices_to={'level__exact': 0}, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memberprofile_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Primary Industry'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='privacy_email',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Email'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='privacy_phone',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Phone'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='privacy_web',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Web'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='public_website_consent',
            field=models.BooleanField(
                default=False, verbose_name='Public Website Consent'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='referred_by',
            field=models.TextField(
                blank=True,
                help_text=REFERRED_BY_HELP_TEXT,
                max_length=500),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='speaker_interest',
            field=models.BooleanField(
                default=False, help_text=SPEAKER_INTEREST_HELP_TEXT,
                verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='speaker_topics',
            field=models.TextField(
                blank=True,
                help_text=SPEAKER_TOPICS_HELP_TEXT,
                verbose_name='Speaker Topics'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='title',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Professional Title'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True, help_text=ADDITIONAL_INDUSTRIES_HELP_TEXT,
                related_name='expertprofile_secondary_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='company',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='expert_category',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expertprofile_experts',
                to=settings.ACCELERATOR_EXPERTCATEGORY_MODEL,
                verbose_name='I primarily consider myself a(n)'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='functional_expertise',
            field=models.ManyToManyField(
                blank=True, related_name='expertprofile_experts',
                to=settings.MPTT_SWAPPABLE_FUNCTIONALEXPERTISE_MODEL,
                verbose_name='Functional Expertise'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='home_program_family',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL,
                verbose_name='Home Program Family'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='primary_industry',
            field=models.ForeignKey(
                blank=True, limit_choices_to={'level__exact': 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='expertprofile_experts',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Primary Industry'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='privacy_email',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Email'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='privacy_phone',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Phone'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='privacy_web',
            field=models.CharField(
                blank=True, choices=PRIVACY_CHOICES,
                default='finalists and staff', max_length=64,
                verbose_name='Privacy - Web'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='title',
            field=models.CharField(
                blank=True, max_length=255,
                verbose_name='Professional Title'),
        ),
    ]
