# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 10:21
from __future__ import unicode_literals

from django.db import migrations
from accelerator.side_nav_tree_utils import (
    add_user_roles_to_items,
    create_items
)


def add_items_to_side_nav_tree(apps, schema_editor):
    create_items()
    add_user_roles_to_items()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0042_create_side_nav_tree'),
    ]

    operations = [
        migrations.RunPython(add_items_to_side_nav_tree),
    ]
