# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-20 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0042_change_end_and_start_date_time_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navtreeitem',
            name='program_exclude',
        ),
        migrations.RemoveField(
            model_name='navtreeitem',
            name='program_family_exclude',
        ),
    ]
