# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-19 09:55
from __future__ import unicode_literals

from django.db import migrations
from accelerator.side_nav_tree_utils import MC_SIDE_NAV_TREE_ALIAS


def create_side_nav_tree(apps, schema_editor):
    NavTree = apps.get_model('accelerator', 'NavTree')
    side_nav_tree = NavTree(
        title="MC Side Nav Tree",
        alias=MC_SIDE_NAV_TREE_ALIAS)
    side_nav_tree.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0042_change_end_and_start_date_time_fields'
        ),
    ]

    operations = [
        migrations.RunPython(create_side_nav_tree),
    ]
