# Generated by Django 2.2.10 on 2021-05-26 20:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


JUDGE_TYPE_HELP_TEXT = ('Allowed Values: 1 - Round 1 Judge, 2 - Round 2 '
                        'Judge, 3 - Pre-final Judge, 4 - Final Judge, 0 - '
                        'Once Accepted, now rejected, X - Not Accepted as a '
                        'Judge (May still be a mentor)')

MENTOR_TYPE_HELP_TEXT = ('Allowed Values: F - Functional Expert, P - Partner, '
                         'T - Technical, E - Entrepreneur, N - Once accepted, '
                         'now rejected, X - Not Accepted as a Mentor (may '
                         'still be a judge)')

MULTI_SELECT_HELP_TEXT = ('Hold down "Control", or "Command" on a Mac,to '
                          'select more than one.')

INTERNAL_NOTES_HELP_TEXT = ('Internal notes only for use by MassChallenge '
                            'Staff (not visible to Expert)')

class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0043_move_user_editable_fields_to_core_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreprofile',
            name='expert_group',
            field=models.CharField(blank=True, max_length=10,
                                   verbose_name='Expert Group'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='internal_notes',
            field=models.TextField(blank=True,
                                   help_text=INTERNAL_NOTES_HELP_TEXT,
                                   max_length=500),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='judge_type',
            field=models.CharField(blank=True,
                                   help_text=JUDGE_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Judge Type'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='mentor_type',
            field=models.CharField(blank=True,
                                   help_text=MENTOR_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Mentor Type'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='_coreprofile_mentoring_specialties_',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='public_website_consent_checked',
            field=models.BooleanField(
                default=False,
                verbose_name='Public Website Consent Check'),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='reliability',
            field=models.DecimalField(blank=True,
                                      decimal_places=2,
                                      default=Decimal('1.00'),
                                      max_digits=3,
                                      null=True),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='salutation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='expert_group',
            field=models.CharField(blank=True,
                                   max_length=10,
                                   verbose_name='Expert Group'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='internal_notes',
            field=models.TextField(blank=True,
                                   help_text=INTERNAL_NOTES_HELP_TEXT,
                                   max_length=500),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='judge_type',
            field=models.CharField(blank=True,
                                   help_text=JUDGE_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Judge Type'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='mentor_type',
            field=models.CharField(blank=True,
                                   help_text=MENTOR_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Mentor Type'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='_entrepreneurprofile_mentoring_specialties_',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='public_website_consent_checked',
            field=models.BooleanField(
                default=False,
                verbose_name='Public Website Consent Check'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='reliability',
            field=models.DecimalField(blank=True,
                                      decimal_places=2,
                                      default=Decimal('1.00'),
                                      max_digits=3,
                                      null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='salutation',
            field=models.CharField(blank=True,
                                   max_length=255),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='expert_group',
            field=models.CharField(blank=True,
                                   max_length=10,
                                   verbose_name='Expert Group'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='internal_notes',
            field=models.TextField(blank=True,
                                   help_text=INTERNAL_NOTES_HELP_TEXT,
                                   max_length=500),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='judge_type',
            field=models.CharField(blank=True,
                                   help_text=JUDGE_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Judge Type'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='mentor_type',
            field=models.CharField(blank=True,
                                   help_text=MENTOR_TYPE_HELP_TEXT,
                                   max_length=1,
                                   verbose_name='Mentor Type'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='_memberprofile_mentoring_specialties_',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='public_website_consent_checked',
            field=models.BooleanField(default=False,
                                      verbose_name='Public Website Consent Check'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='reliability',
            field=models.DecimalField(blank=True,
                                      decimal_places=2,
                                      default=Decimal('1.00'),
                                      max_digits=3,
                                      null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='salutation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='_expertprofile_mentoring_specialties_',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
    ]
