# Generated by Django 2.2.10 on 2021-05-25 12:38

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accelerator', '0043_entrepreneurprofile1'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreprofile',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_accelerator.coreprofile_set+',
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile1',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_accelerator.entrepreneurprofile1_set+',
                to='contenttypes.ContentType'),
        ),
    ]
