# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 12:56
from __future__ import unicode_literals

from django.db import migrations

from accelerator.sitetree_navigation.sub_navigation import (
    create_directory_subnav,
    create_events_subnav,
    create_home_subnav,
    create_judging_subnav,
    create_resources_subnav,
    create_startup_dashboard_subnav,
)


def create_subnav_trees_and_items(apps, schema_editor):
    create_directory_subnav()
    create_events_subnav()
    create_home_subnav()
    create_judging_subnav()
    create_resources_subnav()
    create_startup_dashboard_subnav()


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0044_add_sitetree_sidenav_toggle'
        ),
    ]

    operations = [
        migrations.RunPython(create_subnav_trees_and_items),
    ]
