# Generated by Django 2.2.10 on 2021-05-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accelerator', '0044_move_all_fields_from_expert_to_coreprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile1',
            fields=[
                ('coreprofile_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='accelerator.CoreProfile')),
            ],
            options={
                'db_table': 'accelerator_entrepreneurprofile1',
            },
            bases=('accelerator.coreprofile',),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_accelerator.coreprofile_set+',
                to='contenttypes.ContentType'),
        ),
    ]
