# Generated by Django 2.2.10 on 2021-05-25 12:40

from django.conf import settings
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0044_coreprofile_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile1',
            name='id',
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile1',
            name='coreprofile_ptr',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True,
                serialize=False, to=settings.ACCELERATOR_COREPROFILE_MODEL),
        ),
    ]
