# Generated by Django 2.2.10 on 2021-05-26 09:37
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

MULTI_SELECT_HELP_TEXT = ('Hold down "Control", or "Command" on a Mac,to '
                          'select more than one.')


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accelerator', '0045_remove_role_based_redirects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='coreprofile_experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='memberprofile_experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='expertprofile_experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='mentoring_specialties',
            field=models.ManyToManyField(
                blank=True,
                help_text=MULTI_SELECT_HELP_TEXT,
                related_name='entrepreneurprofile_experts',
                to=settings.ACCELERATOR_MENTORINGSPECIALTIES_MODEL,
                verbose_name='Mentoring Specialties'),
        ),
        migrations.CreateModel(
            name='EntrepreneurProfile1',
            fields=[
                ('coreprofile_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='accelerator.CoreProfile')),
            ],
            options={
                'db_table': 'accelerator_entrepreneurprofile1',
            },
            bases=('accelerator.coreprofile',),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='polymorphic_ctype',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='polymorphic_accelerator.coreprofile_set+',
                to='contenttypes.ContentType'),
        ),
    ]
