# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0045_create_startup_dashboard_subnav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navtreeitem',
            name='display_single_item',
            field=models.BooleanField(default=True),
        ),
    ]
