# Generated by Django 2.2.10 on 2021-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0045_update_polymorphic_ctype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntrepreneurProfile',
        ),
    ]
