# Generated by Django 2.2.10 on 2021-05-25 12:41

from django.db import migrations


def migrate_entrepreneur_profile_data(apps, schema_editor):
    EntrepreneurProfile = apps.get_model('accelerator', 'EntrepreneurProfile')
    EntrepreneurProfile1 = apps.get_model('accelerator', 'EntrepreneurProfile1')
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    for profile in EntrepreneurProfile.objects.all():
        ep_dict = profile.__dict__.copy()
        ep_dict.pop("_state")
        ep_dict.pop("id")
        cp = CoreProfile.objects.create(**ep_dict)
        EntrepreneurProfile1.objects.create(coreprofile_ptr_id=cp.pk)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0045_auto_20210525_0840'),
    ]

    operations = [
        migrations.RunPython(migrate_entrepreneur_profile_data,
                             migrations.RunPython.noop),
    ]
