# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_pages', '0005_author_on_delete_set_null'),
        ('accelerator', '0046_add_items_to_side_nav_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSideNavAssociation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, null=True)),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, null=True)),
                (
                    'node',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fluent_pages.UrlNode')),
                (
                    'sub_nav',
                    models.ForeignKey(
                        help_text=(
                            'This is the sub navigation tree '
                            'that this page is tied to'
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ACCELERATOR_NAVTREE_MODEL)),
            ],
            options={
                'verbose_name': 'Node Side Navigation Association',
                'verbose_name_plural': 'Node Side Navigation Associations',
                'db_table': 'accelerator_nodesidenavassociation',
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_NODESIDENAVASSOCIATION_MODEL',
            },
        ),
        migrations.AlterField(
            model_name='navtreeitem',
            name='display_single_item',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nodesidenavassociation',
            name='sub_nav_item',
            field=models.ForeignKey(
                help_text=(
                    'This is the sub navigation item that '
                    'this page is tied to'
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_NAVTREEITEM_MODEL),
        ),
    ]
