# Generated by Django 2.2.10 on 2021-05-26 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0046_delete_entrepreneurprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrepreneurProfile1',
            new_name='EntrepreneurProfile',
        ),
        migrations.AlterModelTable(
            name='entrepreneurprofile',
            table='accelerator_entrepreneurprofile',
        ),
    ]
