# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_pages', '0005_author_on_delete_set_null'),
        ('accelerator', '0046_auto_20190328_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSideNavAssociation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, null=True)
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, null=True)
                ),
                (
                    'node',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='fluent_pages.UrlNode')
                ),
                (
                    'side_nav',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.ACCELERATOR_NAVTREEITEM_MODEL)
                ),
            ],
            options={
                'verbose_name': 'Side Nav Association',
                'verbose_name_plural': 'Node will show up on',
                'db_table': 'accelerator_nodesidenavassociation',
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_NODESIDENAVASSOCIATION_MODEL',
            },
        ),
    ]
