# Generated by Django 2.2.10 on 2021-05-25 12:42

from django.db import migrations
from polymorphic.utils import reset_polymorphic_ctype


def forwards_func(apps, schema_editor):
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    EntrepreneurProfile1 = apps.get_model('accelerator', 'EntrepreneurProfile1')
    reset_polymorphic_ctype(CoreProfile, EntrepreneurProfile1)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0046_auto_20210525_0738'),
    ]

    operations = [
        migrations.RunPython(forwards_func,
                             migrations.RunPython.noop),
    ]
