# Generated by Django 2.2.10 on 2021-05-26 09:37

from django.db import migrations


def migrate_entrepreneur_profile_data(apps, schema_editor):
    EntrepreneurProfile = apps.get_model('accelerator', 'EntrepreneurProfile')
    EntrepreneurProfile1 = apps.get_model(
        'accelerator', 'EntrepreneurProfile1')
    for profile in EntrepreneurProfile.objects.all():
        profile_dict = profile.__dict__.copy()
        profile_dict.pop("_state")
        profile_dict.pop("id")
        ep1 = EntrepreneurProfile1.objects.create(**profile_dict)
        for choice in profile.gender_identity.all():
            ep1.gender_identity.add(choice)
        for industry in profile.additional_industries.all():
            ep1.additional_industries.add(industry)
        for identity in profile.ethno_racial_identification.all():
            ep1.ethno_racial_identification.add(identity)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0046_add_entrepreneurprofile1'),
    ]

    operations = [
        migrations.RunPython(migrate_entrepreneur_profile_data,
                             migrations.RunPython.noop),
    ]
