# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0047_nodesidenavassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesidenavassociation',
            name='side_nav',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_NAVTREE_MODEL),
        ),
    ]
