# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0048_create_sub_navigation_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='location',
            field=models.CharField(
                choices=[
                    ('MassChallenge Boston', 'MassChallenge Boston'),
                    ('MassChallenge Israel - Jerusalem',
                     'MassChallenge Israel - Jerusalem'),
                    ('MassChallenge Israel - Tel Aviv',
                     'MassChallenge Israel - Tel Aviv'),
                    ('MassChallenge Mexico', 'MassChallenge Mexico'),
                    ('MassChallenge Rhode Island',
                     'MassChallenge Rhode Island'),
                    ('MassChallenge Switzerland', 'MassChallenge Switzerland'),
                    ('MassChallenge Texas - Austin',
                     'MassChallenge Texas - Austin'),
                    ('MassChallenge Texas - Houston',
                     'MassChallenge Texas - Houston'),
                    ('Remote - see description', 'Remote - see description'),
                    ('Other - see description', 'Other - see description')],
                max_length=50),
        ),
    ]
