# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-29 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0048_associate_fluent_with_nav_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesidenavassociation',
            name='sub_nav_item',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_NAVTREEITEM_MODEL),
        ),
    ]
