# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-11 11:35
from __future__ import unicode_literals

from django.db import migrations

from accelerator.sitetree_navigation.sub_navigation import (
    create_directory_subnav,
    create_events_subnav,
    create_home_subnav,
    create_judging_subnav,
    create_resources_subnav,
    create_startup_dashboard_subnav,
    delete_directory_subnav,
    delete_events_subnav,
    delete_home_subnav,
    delete_judging_subnav,
    delete_resources_subnav,
    delete_startup_dashboard_subnav
)


def create_subnav_trees_and_items(apps, schema_editor):
    create_directory_subnav()
    create_events_subnav()
    create_home_subnav()
    create_judging_subnav()
    create_resources_subnav()
    create_startup_dashboard_subnav()


def delete_subnav_trees_and_items(apps, schema_editor):
    delete_directory_subnav()
    delete_events_subnav()
    delete_home_subnav()
    delete_judging_subnav()
    delete_resources_subnav()
    delete_startup_dashboard_subnav()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0049_update_office_hour_location_choices'),
    ]

    operations = [
        migrations.RunPython(
            create_subnav_trees_and_items,
            delete_subnav_trees_and_items),
    ]
