# Generated by Django 2.2.10 on 2021-06-02 11:20

from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0051_update_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertProfile1',
            fields=[
                ('coreprofile_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='accelerator.CoreProfile')),
            ],
            options={
                'db_table': 'accelerator_expertprofile1',
                'permissions': (
                    ('change_password', 'Can change users passwords directly'),
                ),
            },
            bases=('accelerator.coreprofile',),
        ),
    ]
