# Generated by Django 2.2.10 on 2021-06-02 11:25

from django.db import migrations


def migrate_expert_profile_data(apps, schema_editor):
    ExpertProfile = apps.get_model('accelerator', 'ExpertProfile')
    ExpertProfile1 = apps.get_model('accelerator', 'ExpertProfile1')
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    exclude = CoreProfile.objects.all().values_list('user_id', flat=True)
    for profile in ExpertProfile.objects.exclude(user_id__in=exclude):
        profile_dict = profile.__dict__.copy()
        profile_dict.pop("_state")
        profile_dict.pop("id")
        ep1 = ExpertProfile1.objects.create(**profile_dict)
        for choice in profile.gender_identity.all():
            ep1.gender_identity.add(choice)
        for industry in profile.additional_industries.all():
            ep1.additional_industries.add(industry)
        for identity in profile.ethno_racial_identification.all():
            ep1.ethno_racial_identification.add(identity)
        
        


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0052_add_expertprofile1'),
    ]

    operations = [
        migrations.RunPython(migrate_expert_profile_data,
                             migrations.RunPython.noop),
    ]
