# Generated by Django 2.2.10 on 2021-05-26 09:37

from django.db import migrations
from polymorphic.utils import reset_polymorphic_ctype


def update_polymorphic_ctype(apps, schema_editor):
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    EntrepreneurProfile = apps.get_model('accelerator', 'EntrepreneurProfile')
    ExpertProfile1 = apps.get_model('accelerator', 'ExpertProfile1')
    reset_polymorphic_ctype(CoreProfile, EntrepreneurProfile, ExpertProfile1)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0052_migrate_expert_profile_data'),
    ]

    operations = [
        migrations.RunPython(update_polymorphic_ctype,
                             migrations.RunPython.noop),
    ]
