# Generated by Django 2.2.10 on 2021-06-02 11:25

from django.db import migrations
from accelerator.utils import copy_m2m_fields


def migrate_expert_profile_data(apps, schema_editor):
    ExpertProfile = apps.get_model('accelerator', 'ExpertProfile')
    ExpertProfile1 = apps.get_model('accelerator', 'ExpertProfile1')
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    exclude = CoreProfile.objects.all().values_list('user_id', flat=True)
    m2m_fields = ['gender_identity', 'interest_categories', 'program_families',
                  'ethno_racial_identification', 'additional_industries',
                  'functional_expertise', 'mentoring_specialties']
    for profile in ExpertProfile.objects.exclude(user_id__in=exclude):
        profile_dict = profile.__dict__.copy()
        profile_dict.pop("_state")
        profile_dict.pop("id")
        new_profile = ExpertProfile1.objects.create(**profile_dict)
        copy_m2m_fields(profile, new_profile, m2m_fields)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0052_add_expertprofile1'),
    ]

    operations = [
        migrations.RunPython(migrate_expert_profile_data,
                             migrations.RunPython.noop),
    ]
