# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0052_cleanup_twitter_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='eventbrite_organization_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
