# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-28 13:59
from __future__ import unicode_literals

from django.db import migrations

from accelerator.sitetree_navigation.sub_navigation import (
    create_startup_dashboard_subnav,
)


def update_startup_dashboard_subnav_items(apps, schema_editor):
    create_startup_dashboard_subnav()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0053_add_eventbrite_organization_id_field'),
    ]

    operations = [
        migrations.RunPython(
            update_startup_dashboard_subnav_items,
            migrations.RunPython.noop),
    ]
