# Generated by Django 2.2.10 on 2021-06-02 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0053_update_polymorphic_ctype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertProfile',
        ),
    ]
