# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-28 13:59
from __future__ import unicode_literals

from django.db import migrations

from accelerator.sitetree_navigation.sub_navigation import (
    create_startup_dashboard_subnav,
    STARTUP_PROFILE_ALIAS,
)


def update_startup_dashboard_subnav_items(apps, schema_editor):
    create_startup_dashboard_subnav()
    NavTreeItem = apps.get_model('accelerator', 'NavTreeItem')
    profile_item = NavTreeItem.objects.filter(
        alias=STARTUP_PROFILE_ALIAS).first()
    view_profile_item = NavTreeItem.objects.filter(
        alias='startup_view').first()
    edit_profile_item = NavTreeItem.objects.filter(
        alias='startup_edit').first()
    if profile_item and view_profile_item:
        view_profile_item.parent = profile_item
        view_profile_item.save()
    if profile_item and edit_profile_item:
        edit_profile_item.parent = profile_item
        edit_profile_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0053_add_eventbrite_organization_id_field'),
    ]

    operations = [
        migrations.RunPython(
            update_startup_dashboard_subnav_items,
            migrations.RunPython.noop),
    ]
