# Generated by Django 2.2.10 on 2021-05-26 10:40

from django.db import migrations
from polymorphic.utils import reset_polymorphic_ctype


def update_polymorphic_ctype(apps, schema_editor):
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    EntrepreneurProfile = apps.get_model('accelerator', 'EntrepreneurProfile')
    ExpertProfile = apps.get_model('accelerator', 'ExpertProfile')
    reset_polymorphic_ctype(CoreProfile, EntrepreneurProfile, ExpertProfile)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0055_rename_expert_profile'),
    ]

    operations = [
        migrations.RunPython(update_polymorphic_ctype,
                             migrations.RunPython.noop),
    ]
