# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-03 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0056_revoke_delete_user_perms_from_non_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearance',
            name='level',
            field=models.CharField(choices=[('Exec/MD', 'Exec/MD'), ('Global Manager', 'Global Manager'), ('Program Operations Manager', 'Program Operations Manager'), ('Staff', 'Staff')], max_length=64),
        ),
    ]
