# Generated by Django 2.2.10 on 2021-06-08 14:37

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

from accelerator.utils import copy_m2m_fields


def migrate_member_profile_data(apps, schema_editor):
    MemberProfile = apps.get_model('accelerator', 'MemberProfile')
    MemberProfile1 = apps.get_model('accelerator', 'MemberProfile1')
    CoreProfile = apps.get_model('accelerator', 'CoreProfile')
    exclude = CoreProfile.objects.all().values_list('user_id', flat=True)
    m2m_fields = ['gender_identity', 'interest_categories', 'program_families',
                  'ethno_racial_identification', 'additional_industries',
                  'functional_expertise', 'mentoring_specialties']
    for profile in MemberProfile.objects.exclude(user_id__in=exclude):
        profile_dict = profile.__dict__.copy()
        profile_dict.pop("_state")
        profile_dict.pop("id")
        new_profile = MemberProfile1.objects.create(**profile_dict)
        copy_m2m_fields(profile, new_profile, m2m_fields)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0057_update_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile1',
            fields=[
                ('coreprofile_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     serialize=False,
                     to='accelerator.CoreProfile')),
            ],
            options={
                'db_table': 'accelerator_memberprofile1',
            },
            bases=('accelerator.coreprofile',),
        ),
        migrations.RunPython(migrate_member_profile_data,
                             migrations.RunPython.noop),
    ]
