# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-26 13:08
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission

from accelerator.utils import create_mc_permission


def add_mc_nodesubnavigation_permissions(apps, schema_editor):
    permissions = Permission.objects.filter(
        content_type__app_label='accelerator',
        content_type__model='nodesubnavassociation')
    for permission in permissions:
        create_mc_permission(permission)


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0058_grant_staff_clearance_for_existing_staff_members'
        ),
    ]

    operations = [
        migrations.RunPython(add_mc_nodesubnavigation_permissions,
                             migrations.RunPython.noop)
    ]
