# Generated by Django 2.2.10 on 2021-06-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0059_update_polymorphic_ctype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
