# Generated by Django 2.2.10 on 2021-06-08 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0060_delete_memberprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProfile1',
            new_name='MemberProfile',
        ),
        migrations.AlterModelTable(
            name='memberprofile',
            table='accelerator_memberprofile',
        ),
    ]
