# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0061_remove_eventbrite_organization_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfamily',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone name from Olson Timezone database (https://en.wikipedia.org/wiki/Tz_database)', max_length=35),
        ),
    ]
