# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 13:10
from __future__ import unicode_literals

from django.db import migrations

from accelerator_abstract.models.base_startup_role import BaseStartupRole


def remove_eit_only_finalists_from_alumni_program(apps, schema_editor):
    ProgramFamily = apps.get_model('accelerator', 'ProgramFamily')
    ProgramRoleGrant = apps.get_model('accelerator', 'ProgramRoleGrant')
    StartupStatus = apps.get_model('accelerator', 'StartupStatus')
    StartupTeamMember = apps.get_model('accelerator', 'StartupTeamMember')

    alum_program_family = ProgramFamily.objects.filter(
        name="Global Alumni Program").first()
    eit_program_family = ProgramFamily.objects.filter(
        name="EIT Food Accelerator").first()

    eit_finalist_startups = StartupStatus.objects.filter(
        program_startup_status__program__program_family=eit_program_family,
        program_startup_status__startup_role__name=BaseStartupRole.FINALIST
        ).values_list("startup", flat=True)

    eit_alum_startup_statuses = StartupStatus.objects.filter(
        startup_id__in=eit_finalist_startups,
        program_startup_status__program__program_family=alum_program_family
        )

    eit_alum_startups = eit_alum_startup_statuses.values_list(
        "startup", flat=True)

    eit_alums = StartupTeamMember.objects.filter(
        startup__in=eit_alum_startups
        ).values_list('user', flat=True)

    ProgramRoleGrant.objects.filter(
        person_id__in=eit_alums,
        program_role__program__program_family=alum_program_family
        ).delete()

    eit_alum_startup_statuses.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0061_remove_eventbrite_organization_id_field'),
    ]

    operations = [
        migrations.RunPython(
            remove_eit_only_finalists_from_alumni_program,
            migrations.RunPython.noop)
    ]
