# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-02 19:49
from __future__ import unicode_literals
from django.db import migrations

timezones = {
    'Boston': "America/New_York",
    "UK": "UTC",
    "Israel": "Israel",
    "MADE": "America/New_York",
    "Mexico": "America/Mexico_City",
    "Switzerland": "Europe/Zurich",
    "Texas - Austin": "America/Chicago",
    "Texas - Houston": "America/Chicago",
    "HealthTech": "America/New_York",
    "FinTech": "America/New_York",
    "Bridge to MassChallenge Biscay": "Europe/Madrid",
    "Rhode Island": "America/New_York",
    "EIT Food Accelerator": "Europe/Zurich",
    "Startup HUB CDMX from Facebook by MassChallenge Mexico":
        "America/Mexico_City",
    "Global Alumni Program": "UTC",
    "Demo Days": "UTC",
    "Comet (Boston)": "America/New_York",
    "Comet (Texas)": "America/Chicago",
    "Comet (Israel)": "Israel",
    "Impulse Accelerator": "America/New_York"
}


def update_timezone_for_programfamily(apps, schema_editor):
    ProgramFamily = apps.get_model("accelerator", "ProgramFamily")
    for program_family in ProgramFamily.objects.all():
        program_family.timezone = timezones.get(program_family.name, 'UTC')
        program_family.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0063_add_timezone_to_program_family'),
    ]

    operations = [
        migrations.RunPython(
            update_timezone_for_programfamily,
            migrations.RunPython.noop)
    ]
