# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-01 19:59
from __future__ import unicode_literals
from datetime import (
    datetime,
    timedelta,
)
from pytz import (
    timezone,
    utc,
)
from django.db import migrations


one_day = timedelta(1)


def migrate_date_time_data(apps, schema_editor):
    MentorProgramOfficeHour = apps.get_model('accelerator',
                                             'MentorProgramOfficeHour')
    for office_hour in MentorProgramOfficeHour.objects.all():
        migrate_office_hour_time_data(office_hour)


def migrate_office_hour_time_data(office_hour):
    tz = timezone(office_hour.program.program_family.timezone)
    office_hour.start_date_time = as_utc(office_hour.date,
                                         office_hour.start_time,
                                         tz)
    office_hour.end_date_time = as_utc(office_hour.date,
                                       office_hour.end_time,
                                       tz)
    if office_hour.end_date_time < office_hour.start_date_time:
        office_hour.end_date_time += one_day
    office_hour.save()


def as_utc(date, time, local_timezone):
    local_time = local_timezone.localize(datetime.combine(date, time))
    return local_time.astimezone(utc)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0064_add_sane_date_time_fields_to_office_hours_model'),
    ]

    operations = [
        migrations.RunPython(
            migrate_date_time_data,
            migrations.RunPython.noop)
    ]
