# Generated by Django 2.2.10 on 2021-07-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0064_update_gender_criteria_to_full_gender_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernote',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='usernote_notes',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrganizationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, 
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    null=True)),
                ('updated_at', models.DateTimeField(auto_now=True,
                                                    null=True)),
                ('note_content', models.TextField(default='',
                                                  help_text='Note contents')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='organizationnote_notes',
                                   to=settings.AUTH_USER_MODEL)),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='organization_notes',
                                   to=settings.ACCELERATOR_ORGANIZATION_MODEL)),
            ],
            options={
                'verbose_name': 'Organization note',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
