# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-01 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0064_fill_in_program_family_timezones'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='end_date_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='start_date_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
