# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-11 20:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0065_migrate_date_and_time_data_for_office_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorprogramofficehour',
            options={'managed': True, 'ordering': ['start_date_time'], 'verbose_name': 'Office Hour'},
        ),
        migrations.AlterUniqueTogether(
            name='mentorprogramofficehour',
            unique_together=set([('program', 'mentor', 'start_date_time')]),
        ),
    ]
