# Generated by Django 2.2.24 on 2021-08-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0066_partnerjudginginstructions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partnerjudginginstructions',
            table=None,
        ),
    ]
