# Generated by Django 2.2.10 on 2021-08-27 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0067_partnerjudgingroundchallenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerJudgingInstructions',
            fields=[
                ('id', models.AutoField(
                                        auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(
                                        auto_now_add=True,
                                        null=True)),
                ('updated_at', models.DateTimeField(
                                        auto_now=True,
                                        null=True)),
                ('instructions', models.TextField(
                    help_text='Partner Judging instructions')),
                ('judging_round', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_JUDGINGROUND_MODEL)),
                ('partner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_PARTNER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Partner judging Round instructions',
                'db_table': 'accelerator_partnerjudginginstructions',
                'abstract': False,
                'managed': True,
                'swappable': 'ACCELERATOR_PARTNERJUDGINGINSTRUCTIONS_MODEL',
                'unique_together': {('partner', 'judging_round')},
            },
        ),
    ]
