# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-11 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0067_update_unique_and_ordering_for_office_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprogramofficehour',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mentorprogramofficehour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='mentorprogramofficehour',
            name='start_time',
        ),
    ]
