# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-29 09:09
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0067_update_unique_and_ordering_for_office_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='end_date_time',
            field=models.DateTimeField(
                db_index=True, null=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='start_date_time',
            field=models.DateTimeField(
                db_index=True, null=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='end_date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='start_date_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
