# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0069_make_start_and_end_date_time_fields_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcheck',
            name='is_enabled_for_entrepreneurs',
            field=models.BooleanField(default=True, help_text='This legal check is for Entrepreneurs (people with Startups applying to MassChallenge)'),
        ),
        migrations.AddField(
            model_name='legalcheck',
            name='is_enabled_for_experts',
            field=models.BooleanField(default=True, help_text='This legal check is for Experts (Judges and Mentors)'),
        ),
    ]
