# Generated by Django 2.2.10 on 2021-08-31 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0069_partnerstartupinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='judginground',
            name='champion_partner_label',
            field=models.ForeignKey(blank=True,
            help_text='Partner Label',
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            to=settings.ACCELERATOR_PARTNERLABEL_MODEL),
        ),
    ]
