# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'accelerator',
            '0069_make_start_and_end_date_time_fields_non_nullable'
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='test_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
