# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 11:21
from __future__ import unicode_literals
import swapper

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0069_make_start_and_end_date_time_fields_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    null=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(
                    blank=True,
                    default='',
                    max_length=100)),
                ('state', models.CharField(
                    blank=True,
                    default='',
                    max_length=100)),
                ('country', models.CharField(
                    blank=True,
                    default='',
                    max_length=100)),
                ('postcode', models.CharField(
                    blank=True,
                    default='',
                    max_length=20)),
                ('latitude', models.CharField(
                    blank=True,
                    default='',
                    max_length=100)),
                ('longitude', models.CharField(
                    blank=True,
                    default='',
                    max_length=100)),
                ('timezone', models.CharField(
                    default='UTC',
                    help_text=('Timezone name from Olson Timezone '
                               'database (https://en.wikipedia.org'
                               '/wiki/Tz_database)'),
                    max_length=35)),
            ],
            options={
                'verbose_name_plural': 'locations',
                'db_table': 'accelerator_location',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting('accelerator',
                                                       'Location'),
            },
        ),
    ]
