# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-05 16:18
from __future__ import unicode_literals

from django.db import migrations

def long_migation(apps, schema_editor):
    User = apps.get_model('simpleuser',
                          'User')
    for user in User.objects.all():
        user.first_name += "0070"
        user.save()
    
        
class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0069_make_start_and_end_date_time_fields_non_nullable'),
    ]

    operations = [
        migrations.RunPython(long_migration,
                             migrations.RunPython.noop)
    ]
