# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0071_add_program_family_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(
                blank=True,
                default='',
                help_text='State/Region/Province',
                max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(
                default='UTC',
                help_text='Timezone name from Olson Timezone database'
                          ' (https://en.wikipedia.org/wiki/Tz_database, '
                          'https://en.wikipedia.org/wiki/'
                          'List_of_tz_database_time_zones)',
                max_length=35),
        ),
    ]
