# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-07 11:43
from __future__ import unicode_literals
import swapper

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0071_add_smart_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramFamilyLocation',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True,
                    null=True)),
                ('primary', models.BooleanField()),
                ('location', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_LOCATION_MODEL)),
                ('program_family', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_PROGRAMFAMILY_MODEL)),
            ],
            options={
                'verbose_name': 'Program Family Location',
                'verbose_name_plural': 'Program Family Locations',
                'db_table': 'accelerator_programfamilylocation',
                'abstract': False,
                'managed': True,
                'swappable': swapper.swappable_setting(
                    'accelerator',
                    'ProgramFamilyLocation'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='programfamilylocation',
            unique_together=set([('program_family', 'location')]),
        ),
    ]
