# Generated by Django 2.2.10 on 2021-09-07 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


MODEL_LABEL = 'ACCELERATOR_PARTNERJUDGEAPPLICATIONASSIGNMENT_MODEL'
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accelerator', '0071_partnerteammember_champion_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerJudgeApplicationAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('application', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_APPLICATION_MODEL)),
                ('judge', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
                ('judging_round', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_JUDGINGROUND_MODEL)),
                ('partner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.ACCELERATOR_PARTNER_MODEL)),
            ],
            options={
                'db_table': 'accelerator_partnerjudgeapplicationassignment',
                'abstract': False,
                'managed': True,
                'swappable': MODEL_LABEL,
            },
        ),
    ]
