# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-19 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0073_updated_location_fields_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='facebook_url',
            field=models.URLField(
                blank=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='linked_in_url',
            field=models.URLField(
                blank=True, verbose_name='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True, max_length=255, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True, max_length=40, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='facebook_url',
            field=models.URLField(
                blank=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='linked_in_url',
            field=models.URLField(
                blank=True, verbose_name='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True, max_length=255, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True, max_length=40, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='facebook_url',
            field=models.URLField(
                blank=True, verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='linked_in_url',
            field=models.URLField(
                blank=True, verbose_name='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='personal_website_url',
            field=models.URLField(
                blank=True, max_length=255, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='twitter_handle',
            field=models.CharField(
                blank=True, max_length=40, verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='twitter_handle',
            field=models.CharField(
                blank=True,
                help_text='Omit the "@". We\'ll add it.',
                max_length=40,
                verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(
                blank=True, max_length=100, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='facebook_url',
            field=models.URLField(
                blank=True,
                max_length=100,
                verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='linked_in_url',
            field=models.URLField(
                blank=True,
                max_length=100,
                verbose_name='LinkedIn profile URL'),
        ),
    ]
