# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0073_updated_location_fields_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprogramofficehour',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
