# Generated by Django 2.2.10 on 2021-11-12 18:09

from django.db import migrations
from simpleuser.models import User
from accelerator_abstract.models.base_user_utils import is_employee


def remove_finalist_role_from_staff(apps, schema_editor):
    ProgramRoleGrant = apps.get_model("accelerator", "ProgramRoleGrant")
    staff_ids = []
    finalist_users = User.objects.filter(
              programrolegrant__program_role__user_role__name='Finalist')

    for user in finalist_users:
        if is_employee(user):
            staff_ids.append(user.id)

    ProgramRoleGrant.objects.filter(
                program_role__user_role__name='Finalist',
                person_id__in=staff_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0074_update_url_to_community'),
    ]

    operations = [
        migrations.RunPython(remove_finalist_role_from_staff,
                             migrations.RunPython.noop)
    ]
