# Generated by Django 2.2.10 on 2021-11-12 18:09

from django.db import migrations
from simpleuser.models import User


def remove_finalist_role_from_staff(apps, schema_editor):
    ProgramRoleGrant = apps.get_model("accelerator", "ProgramRoleGrant")
    staff_ids = User.objects.filter(
        programrolegrant__program_role__user_role__name='Finalist',
        is_staff=True).values_list('id', flat=True)

    staff_finalist_role = ProgramRoleGrant.objects.filter(
                program_role__user_role__name='Finalist',
                person_id__in=staff_ids).values_list(
                    'id', flat=True)

    for role_id in staff_finalist_role:
        ProgramRoleGrant.objects.get(id=role_id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0074_update_url_to_community'),
    ]

    operations = [
        migrations.RunPython(remove_finalist_role_from_staff,
                             migrations.RunPython.noop)
    ]
