# Generated by Django 2.2.10 on 2021-11-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0074_update_url_to_community'),
    ]

    operations = [
    ]
