# Generated by Django 2.2.10 on 2021-11-24 16:41

from django.db import migrations


def update_panels_url(apps, schema_editor):
    NavTreeItem = apps.get_model('accelerator', 'NavTreeItem')
    NavTreeItem.objects.filter(url='/panels/').update(url='/judging/panels/')


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0075_remove_finalist_role_from_staff'),
    ]
    operations = [
        migrations.RunPython(update_panels_url,
                             migrations.RunPython.noop)
    ]
