# Generated by Django 2.2.10 on 2021-12-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0076_update_sitetree_panels_view_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerapplicationinterest',
            unique_together={('partner', 'judging_round', 'application')},
        ),
    ]
