# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0076_change_description_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_overview_link',
            field=models.URLField(
                blank=True,
                null=True,
                help_text=('URL of the program overview page, '
                            'ex: https://masschallenge.org/programs-boston'),
                max_length=255,
            )
        )
    ]
