# Generated by Django 2.2.10 on 2021-11-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0076_update_sitetree_panels_view_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplicationinterest',
            name='application',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_APPLICATION_MODEL,
                unique=True),
        ),
        migrations.AlterField(
            model_name='partnerapplicationinterest',
            name='judging_round',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_JUDGINGROUND_MODEL,
                unique=True),
        ),
        migrations.AlterField(
            model_name='partnerapplicationinterest',
            name='partner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_PARTNER_MODEL,
                unique=True),
        ),
    ]
