# Generated by Django 2.2.24 on 2021-11-29 12:36

from django.db import migrations


def update_judging_commitment_view_url(apps, schema_editor):
    NavTreeItem = apps.get_model('accelerator', 'NavTreeItem')
    NavTreeItem.objects.filter(
        url='/expert/commitments/').update(url='/judging/commitments/')


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0076_update_sitetree_panels_view_url'),
    ]

    operations = [
        migrations.RunPython(update_judging_commitment_view_url,
                             migrations.RunPython.noop)
    ]
