# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-05 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0077_add_program_overview_link_field_to_a_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprogramofficehour',
            old_name='location',
            new_name='old_location',
        ),
    ]
