# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-06 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0078_rename_location_field_to_old_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprogramofficehour',
            name='location',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.ACCELERATOR_LOCATION_MODEL),
        ),
    ]
