# Generated by Django 2.2.10 on 2022-01-31 11:44

from django.db import migrations, models

PARTICIPATION_ROLE = 'PARTICIPATION_ROLE'
ADVISING_STARTUP_BUSINESS_AREA = 'ADVISING_STARTUP_BUSINESS_AREA'
ADVISING_STARTUP_SUPPORT_BELIEVE = 'ADVISING_STARTUP_SUPPORT_BELIEVE'

PARTICIPATION_CHOICES = (
    (PARTICIPATION_ROLE, PARTICIPATION_ROLE),
    (ADVISING_STARTUP_BUSINESS_AREA, ADVISING_STARTUP_BUSINESS_AREA),
    (ADVISING_STARTUP_SUPPORT_BELIEVE, ADVISING_STARTUP_SUPPORT_BELIEVE)
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0078_auto_20211207_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityParticipation',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('type', models.CharField(
                    choices=PARTICIPATION_CHOICES,
                    default=PARTICIPATION_ROLE,
                    max_length=50)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='community_participation',
            field=models.ManyToManyField(
                blank=True,
                related_name='profiles',
                to='accelerator.CommunityParticipation'),
        ),
    ]
