# Generated by Django 2.2.10 on 2022-02-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0078_auto_20211207_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'managed': True, 'verbose_name_plural': 'Startups'},
        ),
    ]
