# Generated by Django 2.2.10 on 2022-02-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0083_add_unified_profile_legal_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreprofile',
            name='privacy_profile',
            field=models.CharField(
                blank=True, choices=[
                    ('staff', 'MC Staff Only'),
                    ('finalists and staff', 'Finalists and MC Staff'),
                    ('public', 'All Users')],
                default='finalists and staff',
                max_length=64,
                verbose_name='Privacy - Profile'),
        ),
    ]
