# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0085_update_geographic_experience_field_type')
    ]

    operations = [
        migrations.AlterField(
            model_name='startupteammember',
            name='founder',
            field=models.BooleanField(default=False),
        ),
    ]
