# Generated by Django 2.2.10 on 2022-03-16 19:25

from django.db import migrations, models

from accelerator_abstract.models.base_business_proposition import(
    DRIVER_HELP_TEXT,
    COMPETITORS_HELP_TEXT,
    IMPACT_HELP_TEXT,
    INTELLECTUAL_PROPERTY_HELP_TEXT,
    INVESTORS_HELP_TEXT,
    MARKET_HELP_TEXT,
    REGULATORY_HELP_TEXT,
    PAIN_POINT_HELP_TEXT,
    PRODUCT_COMPLEMENT_HELP_TEXT,
    PRIMARY_ADVANTAGE_HELP_TEXT,
    SOLUTION_HELP_TEXT,
    SALES_HELP_TEXT,
    TEAM_SUMMARY_HELP_TEXT,
    VALIDATION_HELP_TEXT,
    VALUE_PROPOSITION_HELP_TEXT,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0090_update_coreprofile_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposition',
            name='competitors',
            field=models.TextField(
                blank=True,
                help_text=COMPETITORS_HELP_TEXT,
                null=True,
                verbose_name='Current and Future Competitors'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='drivers',
            field=models.TextField(
                blank=True,
                help_text=DRIVER_HELP_TEXT,
                null=True,
                verbose_name='Key Drivers of Business Economics'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='impact',
            field=models.TextField(
                blank=True,
                help_text=IMPACT_HELP_TEXT,
                null=True,
                verbose_name='One-Year / Five-Year Impact (?)'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='intellectual_property',
            field=models.TextField(
                blank=True,
                help_text=INTELLECTUAL_PROPERTY_HELP_TEXT,
                null=True,
                verbose_name='Intellectual Property'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='investors',
            field=models.TextField(
                blank=True,
                help_text=INVESTORS_HELP_TEXT,
                null=True,
                verbose_name='Current or anticipated advisors or investors'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='market',
            field=models.TextField(
                blank=True,
                help_text=MARKET_HELP_TEXT,
                null=True,
                verbose_name='Potential Market / Addressable Size'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='pain_point',
            field=models.TextField(
                blank=True,
                help_text=PAIN_POINT_HELP_TEXT,
                null=True,
                verbose_name='Customer Pain Point'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='primary_advantages',
            field=models.TextField(
                blank=True,
                help_text=PRIMARY_ADVANTAGE_HELP_TEXT,
                null=True,
                verbose_name='Primary Advantages vs Competitors'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='product_complements',
            field=models.TextField(
                blank=True,
                help_text=PRODUCT_COMPLEMENT_HELP_TEXT,
                null=True,
                verbose_name='Product Complements / Value Chain Partners'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='regulation',
            field=models.TextField(
                blank=True,
                help_text=REGULATORY_HELP_TEXT,
                null=True,
                verbose_name='Regulatory Requirements'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='sales',
            field=models.TextField(
                blank=True,
                help_text=SALES_HELP_TEXT,
                null=True,
                verbose_name='Sales and Distribution / Channels'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='solution',
            field=models.TextField(
                blank=True,
                help_text=SOLUTION_HELP_TEXT,
                null=True,
                verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='team_summary',
            field=models.TextField(
                blank=True,
                help_text=TEAM_SUMMARY_HELP_TEXT,
                null=True,
                verbose_name='Team (Backgrounds, advantages)'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='validation',
            field=models.TextField(
                blank=True,
                help_text=VALIDATION_HELP_TEXT,
                null=True,
                verbose_name='Traction and Market Validation'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='value_proposition',
            field=models.TextField(
                blank=True,
                help_text=VALUE_PROPOSITION_HELP_TEXT,
                null=True,
                verbose_name='Value Proposition / Marketing Message'),
        )
    ]
