# Generated by Django 2.2.10 on 2022-03-18 16:45

from django.db import migrations, models
from accelerator_abstract.models.base_business_proposition import (
    IMPACT_HELP_TEXT,
    PRODUCT_COMPLEMENT_HELP_TEXT,
    PRIMARY_ADVANTAGE_HELP_TEXT,
    SALES_HELP_TEXT,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0091_business_proposition_help_text_20220316_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposition',
            name='primary_advantages',
            field=models.TextField(
                blank=True,
                help_text=PRIMARY_ADVANTAGE_HELP_TEXT,
                null=True,
                verbose_name='Primary Advantages vs Competitors'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='product_complements',
            field=models.TextField(
                blank=True,
                help_text=PRODUCT_COMPLEMENT_HELP_TEXT,
                null=True,
                verbose_name='Product Complements / Value Chain Partners'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='sales',
            field=models.TextField(
                blank=True,
                help_text=SALES_HELP_TEXT,
                null=True,
                verbose_name='Sales and Distribution / Channels'),
        ),
        migrations.AlterField(
            model_name='businessproposition',
            name='impact',
            field=models.TextField(
                blank=True,
                help_text=IMPACT_HELP_TEXT,
                null=True,
                verbose_name='One-Year / Five-Year Impact'),
        ),
    ]
