# Generated by Django 2.2.10 on 2022-03-22 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0092_update_business_proposition_20220318_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposition',
            name='startup',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='business_propositions',
                to=settings.ACCELERATOR_STARTUP_MODEL),
        )
    ]
