# Generated by Django 2.2.24 on 2022-03-24 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0093_add_business_prop_related_name_20220322_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={
                'managed': False,
                'ordering': ['name'],
                'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={
                'managed': False,
                'verbose_name_plural': 'Startups'},
        ),
    ]
