# Generated by Django 2.2.27 on 2022-03-25 08:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0093_add_business_prop_related_name_20220322_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='public_inquiry_email',
            field=models.EmailField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='twitter_handle',
            field=models.CharField(
                blank=True,
                help_text='Omit the "@". We\'ll add it.',
                max_length=40,
                null=True,
                verbose_name='Twitter handle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url_slug',
            field=models.CharField(
                blank=True,
                default='',
                max_length=64,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    message='Letters, numbers, and dashes only.',
                    regex='^[\\w-]+$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website_url',
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='acknowledgement',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text='I understand that my Startup Profile is a'
                          'pre-requisite for applying to any'
                          'MassChallenge Program',
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='additional_industries',
            field=models.ManyToManyField(
                blank=True,
                db_table='accelerator_startup_related_industry',
                help_text='You may select up to 5 related industries.',
                null=True,
                related_name='secondary_startups',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Additional Industries'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='bipoc_founder',
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name='BIPOC Founder'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='community',
            field=models.CharField(
                blank=True,
                choices=[('red', 'Red'),
                         ('blue', 'Blue'),
                         ('green', 'Green')],
                max_length=64,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_founded',
            field=models.CharField(
                blank=True,
                help_text='Month and Year when your startup was founded.',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='facebook_url',
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Facebook profile URL'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='female_or_transgender_founder',
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name='Female or Transgender Founder'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='first_time_founder',
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name='First-time Founder'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='full_elevator_pitch',
            field=models.TextField(
                blank=True,
                help_text='Your startup in 500 characters or less.',
                max_length=500,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='high_resolution_logo',
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to='startup_pics',
                verbose_name='High Resolution Logo'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='is_startup',
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='is_visible',
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text='Startup Profiles will be published to external'
                          'websites through the the API.',
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='linked_in_url',
            field=models.URLField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='LinkedIn profile URL'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_city',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Please specify the city where your main office'
                          '(headquarters) is located. (e.g. Boston)',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_national',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Please specify the country where your main office'
                          '(headquarters) is located',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_postcode',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Please specify the postal code for your main office'
                          '(headquarters). (ZIP code, Postcode, codigo postal,'
                          'etc.)',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_regional',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Please specify the state, region or province where'
                          'your main office (headquarters) is located'
                          '(if applicable).',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_street_address',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Please specify the street address for your'
                          'main office (headquarters).',
                max_length=100,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='primary_industry',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='startups',
                to=settings.MPTT_SWAPPABLE_INDUSTRY_MODEL,
                verbose_name='Primary Industry categorization'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profile_background_color',
            field=models.CharField(
                blank=True,
                default='217181',
                max_length=7,
                null=True,
                validators=[django.core.validators.RegexValidator(
                    '^([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|)$',
                    'Color must be 3 or 6-digit hexecimal number,'
                    'such as FF0000 for red.')]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profile_text_color',
            field=models.CharField(
                blank=True,
                default='FFFFFF',
                max_length=7,
                null=True,
                validators=[django.core.validators.RegexValidator(
                    '^([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|)$',
                    'Color must be 3 or 6-digit hexecimal number,'
                    'such as FF0000 for red.')]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_pitch',
            field=models.CharField(
                blank=True,
                help_text='Your startup in 140 characters or less.',
                max_length=140,
                null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='startup',
            name='video_elevator_pitch_url',
            field=embed_video.fields.EmbedVideoField(
                blank=True,
                help_text='Upload your 1-3 minute video pitch to Vimeo or'
                          'Youtube. Paste the shared link here.',
                max_length=100,
                null=True),
        ),
    ]
