# Generated by Django 2.2.27 on 2022-04-20 11:18

from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0098_update_startup_update_20220408_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreprofile',
            name='program_interest',
            field=models.ManyToManyField(
                blank=True,
                related_name='profiles',
                to=settings.ACCELERATOR_PROGRAM_MODEL),
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='program_location_interest',
            field=models.ManyToManyField(
                blank=True,
                related_name='profiles',
                to=settings.ACCELERATOR_PROGRAMFAMILYLOCATION_MODEL),
        ),
    ]
