# Generated by Django 2.2.28 on 2022-04-20 13:05

import sorl.thumbnail.fields
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD:accelerator/migrations/0101_update_program_model.py
        ('accelerator', '0100_add_innovation_stage_model'),
=======
        ('accelerator', '0099_program_interest_related_changes'),
>>>>>>> 5dfd5bb ([AC-9452] Fix conflicting migrations):accelerator/migrations/0100_update_program_model.py
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hubspot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=sorl.thumbnail.fields.ImageField(
              blank=True,
              null=True
              upload_to='program_images'),
        ),
    ]
