# Generated by Django 2.2.28 on 2022-04-21 15:59

import sorl.thumbnail.fields
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0099_program_interest_related_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCluster',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', sorl.thumbnail.fields.ImageField(
                    blank=True,
                    null=True,
                    upload_to='industry_cluster_images')),
                ('display_priority', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='industry_cluster_interest',
            field=models.ManyToManyField(
                blank=True,
                related_name='profiles',
                to='accelerator.IndustryCluster'),
        ),
        migrations.AddField(
            model_name='program',
            name='supported_industry_clusters',
            field=models.ManyToManyField(
                blank=True,
                related_name='programs',
                to='accelerator.IndustryCluster'),
        ),
    ]
