# Generated by Django 2.2.28 on 2022-05-09 11:20

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0102_update_program_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupupdate',
            name='acquired_valuation_usd',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Valuation (in US dollars)'),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='active_annualized_revenue_usd',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Annualized revenue (in US dollars)'),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='active_total_funding_usd',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Total Funding Raised (in US dollars)'),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='active_valuation_usd',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Valuation (in US dollars)'),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='currency_type',
            field=models.CharField(
                choices=[
                    ('USD', 'USD'), ('GBP', 'GBP'),
                    ('EUR', 'EUR'), ('JPY', 'JPY'),
                    ('AUD', 'AUD'), ('CAD', 'CAD'),
                    ('CHF', 'CHF'), ('NZD', 'NZD'),
                    ('NGN', 'NGN'), ('MXN', 'MXN')],
                default='USD',
                max_length=5,
                verbose_name='Status Currency'),
        ),
        migrations.AddField(
            model_name='startupupdate',
            name='ipo_valuation_usd',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Valuation (in US dollars)'),
        ),
        migrations.AlterField(
            model_name='startupupdate',
            name='active_annualized_revenue',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Annualized revenue'),
        ),
        migrations.AlterField(
            model_name='startupupdate',
            name='active_total_funding',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Total Funding Raised'),
        ),
        migrations.AlterField(
            model_name='startupupdate',
            name='active_valuation',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=13,
                null=True,
                verbose_name='Valuation'),
        ),
    ]
