# Generated by Django 2.2.10 on 2022-06-06 16:57

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0106_update_partner_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_visible',
            field=models.BooleanField(blank=True, default=True, help_text='Partner Profiles will be published to external websites through the the API.'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location_city',
            field=models.CharField(blank=True, default='', help_text='Please specify the city where your main office (headquarters) is located. (e.g. Boston)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location_national',
            field=models.CharField(blank=True, default='', help_text='Please specify the country where your main office (headquarters) is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location_regional',
            field=models.CharField(blank=True, default='', help_text='Please specify the state, region or province where your main office (headquarters) is located (if applicable).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='location_street_address',
            field=models.CharField(blank=True, default='', help_text='Please specify the street address for your main office (headquarters).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='video_elevator_pitch_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Upload your 1-3 minute video pitch to Vimeo or Youtube. Paste the shared link here.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_city',
            field=models.CharField(blank=True, default='', help_text='Please specify the city where your main office (headquarters) is located. (e.g. Boston)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_national',
            field=models.CharField(blank=True, default='', help_text='Please specify the country where your main office (headquarters) is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_postcode',
            field=models.CharField(blank=True, default='', help_text='Please specify the postal code for your main office (headquarters). (ZIP code, Postcode, codigo postal, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_regional',
            field=models.CharField(blank=True, default='', help_text='Please specify the state, region or province where your main office (headquarters) is located (if applicable).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='location_street_address',
            field=models.CharField(blank=True, default='', help_text='Please specify the street address for your main office (headquarters).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profile_background_color',
            field=models.CharField(blank=True, default='217181', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|)$', 'Color must be 3 or 6-digit hexecimal number, such as FF0000 for red.')]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='profile_text_color',
            field=models.CharField(blank=True, default='FFFFFF', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|)$', 'Color must be 3 or 6-digit hexecimal number, such as FF0000 for red.')]),
        ),
        migrations.AlterField(
            model_name='startup',
            name='video_elevator_pitch_url',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Upload your 1-3 minute video pitch to Vimeo or Youtube. Paste the shared link here.', max_length=100, null=True),
        ),
    ]
