# Generated by Django 2.2.10 on 2022-06-20 16:23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0106_migrate_startup_top_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        )
    ]
