# Generated by Django 2.2.28 on 2022-07-05 15:41

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0109_update_partner_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='full_elevator_pitch',
            field=models.TextField(
                blank=True,
                help_text='Your enterprise in 140 characters or less.',
                max_length=500,
                null=True,
                verbose_name='Detailed Summary'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='short_pitch',
            field=models.TextField(
                blank=True,
                help_text='Your enterprise in 140 characters or less.',
                max_length=140,
                null=True,
                verbose_name='Short Summary'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='video_elevator_pitch_url',
            field=embed_video.fields.EmbedVideoField(
                blank=True,
                help_text='Upload your 1-3 minute video pitch to Vimeo or '
                          'Youtube. Paste the shared link here.',
                max_length=100, null=True, verbose_name='Company Video URL'),
        ),
    ]
