# Generated by Django 2.2.28 on 2022-07-07 14:42

import swapper
from django.db import migrations


def add_partner_profile_top_nav(apps, schema_editor):
    NavTree = swapper.load_model('accelerator', 'NavTree')
    NavTreeItem = apps.get_model('accelerator', 'NavTreeItem')
    NavTreeItem.objects.filter(
        url='/mystartups').update(
            url='/mycompanies', title='My Companies', alias='mycompanies')
    nav_items = [
        {"title": 'Company Profile',
         'alias': 'company_profile',
         'urlaspattern': True,
         'url': 'edit_company_profile partner.organization.id'},
        {"title": 'Team',
         'alias': 'partner_team',
         'urlaspattern': True,
         'url': 'partners_team_list partner.id'},
    ]
    nav_tree, _ = NavTree.objects.get_or_create(
        alias='partner_manager_subnav',
        defaults={'title': 'Partner profile subnav'})

    for item in nav_items:
        defaults = {
            'title': item['title']
        }
        if item.get('urlaspattern', False):
            defaults['urlaspattern'] = item['urlaspattern']
        NavTreeItem.objects.get_or_create(
            alias=item['alias'],
            url=item['url'],
            tree_id=nav_tree.id,
            defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('accelerator', '0111_remove_interest_fields_20220705_0425'),
    ]

    operations = [
        migrations.RunPython(add_partner_profile_top_nav,
                             migrations.RunPython.noop)
    ]
