# Generated by Django 2.2.28 on 2022-07-22 10:13

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ('accelerator', '0113_remove_bucket_list_program_role_20220707_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(
                    auto_now=True, null=True)),
                ('name', models.CharField(
                    max_length=50)),
                ('is_visible', models.BooleanField(
                    default=True)),
                ('display_priority', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='ecosystem_interest',
            field=models.ManyToManyField(
                blank=True,
                related_name='profiles',
                to='accelerator.Ecosystem'),
        ),
        migrations.AddField(
            model_name='program',
            name='supported_ecosystems',
            field=models.ManyToManyField(
                blank=True,
                related_name='programs',
                to='accelerator.Ecosystem'),
        ),
    ]
