# Generated by Django 2.2.10 on 2022-07-18 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
HELP_TEXT = 'Any png or jpg upto to 2mb. Ideal dimensions: 600 x 400 pixels'

class Migration(migrations.Migration):

    dependencies = [
        ('accelerator',
         '0113_remove_bucket_list_program_role_20220707_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True,
                                                    null=True)),
                ('updated_at', models.DateTimeField(auto_now=True,
                                                    null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('logo',
                 sorl.thumbnail.fields.ImageField(help_text=HELP_TEXT,
                                                  upload_to='community_logo',
                                                  verbose_name='Logo')),
                ('image',
                 sorl.thumbnail.fields.ImageField(
                    help_text=HELP_TEXT,
                    upload_to='community_image',
                    verbose_name='Image')),
                ('assignment_order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Community',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='coreprofile',
            name='home_community',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='accelerator.Community',
                verbose_name='home community'),
        ),
        migrations.AddField(
            model_name='programfamily',
            name='home_community',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='accelerator.Community',
                verbose_name='home community'),
        ),
    ]
