# Generated by Django 2.2.10 on 2020-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleuser', '0004_remove_verbose_on_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
