# Generated by Django 2.2.24 on 2021-11-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleuser', '0005_past_due_migrations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
