# Generated by Django 2.2.10 on 2021-11-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleuser', '0006_auto_20211105_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
